/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AccessTypeEnum {
    public static final AccessTypeEnum OFFLINE = new AccessTypeEnum(Value.OFFLINE, "offline");

    private final Value value;

    private final String string;

    AccessTypeEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof AccessTypeEnum && this.string.equals(((AccessTypeEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case OFFLINE:
                return visitor.visitOffline();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AccessTypeEnum valueOf(String value) {
        switch (value) {
            case "offline":
                return OFFLINE;
            default:
                return new AccessTypeEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        OFFLINE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitOffline();

        T visitUnknown(String unknownType);
    }
}
