/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AuthenticatorAttestationResponseData.Builder.class)
public final class AuthenticatorAttestationResponseData {
    private final String attestationObject;

    private final String clientDataJson;

    private final Optional<List<String>> transports;

    private final Map<String, Object> additionalProperties;

    private AuthenticatorAttestationResponseData(
            String attestationObject,
            String clientDataJson,
            Optional<List<String>> transports,
            Map<String, Object> additionalProperties) {
        this.attestationObject = attestationObject;
        this.clientDataJson = clientDataJson;
        this.transports = transports;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("attestationObject")
    public String getAttestationObject() {
        return attestationObject;
    }

    @JsonProperty("clientDataJSON")
    public String getClientDataJson() {
        return clientDataJson;
    }

    @JsonProperty("transports")
    public Optional<List<String>> getTransports() {
        return transports;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AuthenticatorAttestationResponseData
                && equalTo((AuthenticatorAttestationResponseData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AuthenticatorAttestationResponseData other) {
        return attestationObject.equals(other.attestationObject)
                && clientDataJson.equals(other.clientDataJson)
                && transports.equals(other.transports);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.attestationObject, this.clientDataJson, this.transports);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AttestationObjectStage builder() {
        return new Builder();
    }

    public interface AttestationObjectStage {
        ClientDataJsonStage attestationObject(@NotNull String attestationObject);

        Builder from(AuthenticatorAttestationResponseData other);
    }

    public interface ClientDataJsonStage {
        _FinalStage clientDataJson(@NotNull String clientDataJson);
    }

    public interface _FinalStage {
        AuthenticatorAttestationResponseData build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage transports(Optional<List<String>> transports);

        _FinalStage transports(List<String> transports);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AttestationObjectStage, ClientDataJsonStage, _FinalStage {
        private String attestationObject;

        private String clientDataJson;

        private Optional<List<String>> transports = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AuthenticatorAttestationResponseData other) {
            attestationObject(other.getAttestationObject());
            clientDataJson(other.getClientDataJson());
            transports(other.getTransports());
            return this;
        }

        @java.lang.Override
        @JsonSetter("attestationObject")
        public ClientDataJsonStage attestationObject(@NotNull String attestationObject) {
            this.attestationObject = Objects.requireNonNull(attestationObject, "attestationObject must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("clientDataJSON")
        public _FinalStage clientDataJson(@NotNull String clientDataJson) {
            this.clientDataJson = Objects.requireNonNull(clientDataJson, "clientDataJson must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage transports(List<String> transports) {
            this.transports = Optional.ofNullable(transports);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "transports", nulls = Nulls.SKIP)
        public _FinalStage transports(Optional<List<String>> transports) {
            this.transports = transports;
            return this;
        }

        @java.lang.Override
        public AuthenticatorAttestationResponseData build() {
            return new AuthenticatorAttestationResponseData(
                    attestationObject, clientDataJson, transports, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
