/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AuthenticationMethodPassword.Builder.class)
public final class AuthenticationMethodPassword implements IAuthenticationMethodBase {
    private final String id;

    private final OffsetDateTime createdAt;

    private final List<UsageEnum> usage;

    private final String identityUserId;

    private final Optional<OffsetDateTime> lastPasswordReset;

    private final Map<String, Object> additionalProperties;

    private AuthenticationMethodPassword(
            String id,
            OffsetDateTime createdAt,
            List<UsageEnum> usage,
            String identityUserId,
            Optional<OffsetDateTime> lastPasswordReset,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.createdAt = createdAt;
        this.usage = usage;
        this.identityUserId = identityUserId;
        this.lastPasswordReset = lastPasswordReset;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique identifier of the authentication method
     */
    @JsonProperty("id")
    @java.lang.Override
    public String getId() {
        return id;
    }

    /**
     * @return The date and time when the authentication method was created
     */
    @JsonProperty("created_at")
    @java.lang.Override
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("usage")
    @java.lang.Override
    public List<UsageEnum> getUsage() {
        return usage;
    }

    /**
     * @return The ID of the user identity linked with the authentication method
     */
    @JsonProperty("identity_user_id")
    public String getIdentityUserId() {
        return identityUserId;
    }

    /**
     * @return The date of the last password reset
     */
    @JsonProperty("last_password_reset")
    public Optional<OffsetDateTime> getLastPasswordReset() {
        return lastPasswordReset;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AuthenticationMethodPassword && equalTo((AuthenticationMethodPassword) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AuthenticationMethodPassword other) {
        return id.equals(other.id)
                && createdAt.equals(other.createdAt)
                && usage.equals(other.usage)
                && identityUserId.equals(other.identityUserId)
                && lastPasswordReset.equals(other.lastPasswordReset);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.createdAt, this.usage, this.identityUserId, this.lastPasswordReset);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>The unique identifier of the authentication method</p>
         */
        CreatedAtStage id(@NotNull String id);

        Builder from(AuthenticationMethodPassword other);
    }

    public interface CreatedAtStage {
        /**
         * <p>The date and time when the authentication method was created</p>
         */
        IdentityUserIdStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface IdentityUserIdStage {
        /**
         * <p>The ID of the user identity linked with the authentication method</p>
         */
        _FinalStage identityUserId(@NotNull String identityUserId);
    }

    public interface _FinalStage {
        AuthenticationMethodPassword build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage usage(List<UsageEnum> usage);

        _FinalStage addUsage(UsageEnum usage);

        _FinalStage addAllUsage(List<UsageEnum> usage);

        /**
         * <p>The date of the last password reset</p>
         */
        _FinalStage lastPasswordReset(Optional<OffsetDateTime> lastPasswordReset);

        _FinalStage lastPasswordReset(OffsetDateTime lastPasswordReset);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, CreatedAtStage, IdentityUserIdStage, _FinalStage {
        private String id;

        private OffsetDateTime createdAt;

        private String identityUserId;

        private Optional<OffsetDateTime> lastPasswordReset = Optional.empty();

        private List<UsageEnum> usage = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AuthenticationMethodPassword other) {
            id(other.getId());
            createdAt(other.getCreatedAt());
            usage(other.getUsage());
            identityUserId(other.getIdentityUserId());
            lastPasswordReset(other.getLastPasswordReset());
            return this;
        }

        /**
         * <p>The unique identifier of the authentication method</p>
         * <p>The unique identifier of the authentication method</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public CreatedAtStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The date and time when the authentication method was created</p>
         * <p>The date and time when the authentication method was created</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("created_at")
        public IdentityUserIdStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>The ID of the user identity linked with the authentication method</p>
         * <p>The ID of the user identity linked with the authentication method</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("identity_user_id")
        public _FinalStage identityUserId(@NotNull String identityUserId) {
            this.identityUserId = Objects.requireNonNull(identityUserId, "identityUserId must not be null");
            return this;
        }

        /**
         * <p>The date of the last password reset</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage lastPasswordReset(OffsetDateTime lastPasswordReset) {
            this.lastPasswordReset = Optional.ofNullable(lastPasswordReset);
            return this;
        }

        /**
         * <p>The date of the last password reset</p>
         */
        @java.lang.Override
        @JsonSetter(value = "last_password_reset", nulls = Nulls.SKIP)
        public _FinalStage lastPasswordReset(Optional<OffsetDateTime> lastPasswordReset) {
            this.lastPasswordReset = lastPasswordReset;
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllUsage(List<UsageEnum> usage) {
            if (usage != null) {
                this.usage.addAll(usage);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addUsage(UsageEnum usage) {
            this.usage.add(usage);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "usage", nulls = Nulls.SKIP)
        public _FinalStage usage(List<UsageEnum> usage) {
            this.usage.clear();
            if (usage != null) {
                this.usage.addAll(usage);
            }
            return this;
        }

        @java.lang.Override
        public AuthenticationMethodPassword build() {
            return new AuthenticationMethodPassword(
                    id, createdAt, usage, identityUserId, lastPasswordReset, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
