/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AuthenticatorSelection.Builder.class)
public final class AuthenticatorSelection {
    private final Optional<ResidentKeyEnum> residentKey;

    private final Optional<UserVerificationEnum> userVerification;

    private final Map<String, Object> additionalProperties;

    private AuthenticatorSelection(
            Optional<ResidentKeyEnum> residentKey,
            Optional<UserVerificationEnum> userVerification,
            Map<String, Object> additionalProperties) {
        this.residentKey = residentKey;
        this.userVerification = userVerification;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("residentKey")
    public Optional<ResidentKeyEnum> getResidentKey() {
        return residentKey;
    }

    @JsonProperty("userVerification")
    public Optional<UserVerificationEnum> getUserVerification() {
        return userVerification;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AuthenticatorSelection && equalTo((AuthenticatorSelection) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AuthenticatorSelection other) {
        return residentKey.equals(other.residentKey) && userVerification.equals(other.userVerification);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.residentKey, this.userVerification);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<ResidentKeyEnum> residentKey = Optional.empty();

        private Optional<UserVerificationEnum> userVerification = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(AuthenticatorSelection other) {
            residentKey(other.getResidentKey());
            userVerification(other.getUserVerification());
            return this;
        }

        @JsonSetter(value = "residentKey", nulls = Nulls.SKIP)
        public Builder residentKey(Optional<ResidentKeyEnum> residentKey) {
            this.residentKey = residentKey;
            return this;
        }

        public Builder residentKey(ResidentKeyEnum residentKey) {
            this.residentKey = Optional.ofNullable(residentKey);
            return this;
        }

        @JsonSetter(value = "userVerification", nulls = Nulls.SKIP)
        public Builder userVerification(Optional<UserVerificationEnum> userVerification) {
            this.userVerification = userVerification;
            return this;
        }

        public Builder userVerification(UserVerificationEnum userVerification) {
            this.userVerification = Optional.ofNullable(userVerification);
            return this;
        }

        public AuthenticatorSelection build() {
            return new AuthenticatorSelection(residentKey, userVerification, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
