/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AuthenticatorAttachmentEnum {
    public static final AuthenticatorAttachmentEnum CROSS_PLATFORM =
            new AuthenticatorAttachmentEnum(Value.CROSS_PLATFORM, "cross-platform");

    public static final AuthenticatorAttachmentEnum PLATFORM =
            new AuthenticatorAttachmentEnum(Value.PLATFORM, "platform");

    private final Value value;

    private final String string;

    AuthenticatorAttachmentEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof AuthenticatorAttachmentEnum
                        && this.string.equals(((AuthenticatorAttachmentEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CROSS_PLATFORM:
                return visitor.visitCrossPlatform();
            case PLATFORM:
                return visitor.visitPlatform();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AuthenticatorAttachmentEnum valueOf(String value) {
        switch (value) {
            case "cross-platform":
                return CROSS_PLATFORM;
            case "platform":
                return PLATFORM;
            default:
                return new AuthenticatorAttachmentEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PLATFORM,

        CROSS_PLATFORM,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitPlatform();

        T visitCrossPlatform();

        T visitUnknown(String unknownType);
    }
}
