/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AuthenticatorAttestationResponse.Builder.class)
public final class AuthenticatorAttestationResponse {
    private final Optional<AuthenticatorAttachmentEnum> authenticatorAttachment;

    private final Optional<Map<String, Object>> clientExtensionResults;

    private final String id;

    private final String rawId;

    private final AuthenticatorAttestationResponseData response;

    private final AuthenticatorAttestationResponseType type;

    private final Map<String, Object> additionalProperties;

    private AuthenticatorAttestationResponse(
            Optional<AuthenticatorAttachmentEnum> authenticatorAttachment,
            Optional<Map<String, Object>> clientExtensionResults,
            String id,
            String rawId,
            AuthenticatorAttestationResponseData response,
            AuthenticatorAttestationResponseType type,
            Map<String, Object> additionalProperties) {
        this.authenticatorAttachment = authenticatorAttachment;
        this.clientExtensionResults = clientExtensionResults;
        this.id = id;
        this.rawId = rawId;
        this.response = response;
        this.type = type;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("authenticatorAttachment")
    public Optional<AuthenticatorAttachmentEnum> getAuthenticatorAttachment() {
        return authenticatorAttachment;
    }

    @JsonProperty("clientExtensionResults")
    public Optional<Map<String, Object>> getClientExtensionResults() {
        return clientExtensionResults;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("rawId")
    public String getRawId() {
        return rawId;
    }

    @JsonProperty("response")
    public AuthenticatorAttestationResponseData getResponse() {
        return response;
    }

    @JsonProperty("type")
    public AuthenticatorAttestationResponseType getType() {
        return type;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AuthenticatorAttestationResponse && equalTo((AuthenticatorAttestationResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AuthenticatorAttestationResponse other) {
        return authenticatorAttachment.equals(other.authenticatorAttachment)
                && clientExtensionResults.equals(other.clientExtensionResults)
                && id.equals(other.id)
                && rawId.equals(other.rawId)
                && response.equals(other.response)
                && type.equals(other.type);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.authenticatorAttachment,
                this.clientExtensionResults,
                this.id,
                this.rawId,
                this.response,
                this.type);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        RawIdStage id(@NotNull String id);

        Builder from(AuthenticatorAttestationResponse other);
    }

    public interface RawIdStage {
        ResponseStage rawId(@NotNull String rawId);
    }

    public interface ResponseStage {
        TypeStage response(@NotNull AuthenticatorAttestationResponseData response);
    }

    public interface TypeStage {
        _FinalStage type(@NotNull AuthenticatorAttestationResponseType type);
    }

    public interface _FinalStage {
        AuthenticatorAttestationResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage authenticatorAttachment(Optional<AuthenticatorAttachmentEnum> authenticatorAttachment);

        _FinalStage authenticatorAttachment(AuthenticatorAttachmentEnum authenticatorAttachment);

        _FinalStage clientExtensionResults(Optional<Map<String, Object>> clientExtensionResults);

        _FinalStage clientExtensionResults(Map<String, Object> clientExtensionResults);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, RawIdStage, ResponseStage, TypeStage, _FinalStage {
        private String id;

        private String rawId;

        private AuthenticatorAttestationResponseData response;

        private AuthenticatorAttestationResponseType type;

        private Optional<Map<String, Object>> clientExtensionResults = Optional.empty();

        private Optional<AuthenticatorAttachmentEnum> authenticatorAttachment = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AuthenticatorAttestationResponse other) {
            authenticatorAttachment(other.getAuthenticatorAttachment());
            clientExtensionResults(other.getClientExtensionResults());
            id(other.getId());
            rawId(other.getRawId());
            response(other.getResponse());
            type(other.getType());
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public RawIdStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("rawId")
        public ResponseStage rawId(@NotNull String rawId) {
            this.rawId = Objects.requireNonNull(rawId, "rawId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("response")
        public TypeStage response(@NotNull AuthenticatorAttestationResponseData response) {
            this.response = Objects.requireNonNull(response, "response must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("type")
        public _FinalStage type(@NotNull AuthenticatorAttestationResponseType type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage clientExtensionResults(Map<String, Object> clientExtensionResults) {
            this.clientExtensionResults = Optional.ofNullable(clientExtensionResults);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "clientExtensionResults", nulls = Nulls.SKIP)
        public _FinalStage clientExtensionResults(Optional<Map<String, Object>> clientExtensionResults) {
            this.clientExtensionResults = clientExtensionResults;
            return this;
        }

        @java.lang.Override
        public _FinalStage authenticatorAttachment(AuthenticatorAttachmentEnum authenticatorAttachment) {
            this.authenticatorAttachment = Optional.ofNullable(authenticatorAttachment);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "authenticatorAttachment", nulls = Nulls.SKIP)
        public _FinalStage authenticatorAttachment(Optional<AuthenticatorAttachmentEnum> authenticatorAttachment) {
            this.authenticatorAttachment = authenticatorAttachment;
            return this;
        }

        @java.lang.Override
        public AuthenticatorAttestationResponse build() {
            return new AuthenticatorAttestationResponse(
                    authenticatorAttachment, clientExtensionResults, id, rawId, response, type, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
