/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AuthenticationMethodMfaRecoveryCode.Builder.class)
public final class AuthenticationMethodMfaRecoveryCode
        implements IAuthenticationMethodMfaBase, IAuthenticationMethodBase {
    private final boolean confirmed;

    private final Optional<OffsetDateTime> lastAuthAt;

    private final String id;

    private final OffsetDateTime createdAt;

    private final List<UsageEnum> usage;

    private final Map<String, Object> additionalProperties;

    private AuthenticationMethodMfaRecoveryCode(
            boolean confirmed,
            Optional<OffsetDateTime> lastAuthAt,
            String id,
            OffsetDateTime createdAt,
            List<UsageEnum> usage,
            Map<String, Object> additionalProperties) {
        this.confirmed = confirmed;
        this.lastAuthAt = lastAuthAt;
        this.id = id;
        this.createdAt = createdAt;
        this.usage = usage;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The authentication method status
     */
    @JsonProperty("confirmed")
    @java.lang.Override
    public boolean getConfirmed() {
        return confirmed;
    }

    /**
     * @return The date and time when the authentication method was last used
     */
    @JsonProperty("last_auth_at")
    @java.lang.Override
    public Optional<OffsetDateTime> getLastAuthAt() {
        return lastAuthAt;
    }

    /**
     * @return The unique identifier of the authentication method
     */
    @JsonProperty("id")
    @java.lang.Override
    public String getId() {
        return id;
    }

    /**
     * @return The date and time when the authentication method was created
     */
    @JsonProperty("created_at")
    @java.lang.Override
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("usage")
    @java.lang.Override
    public List<UsageEnum> getUsage() {
        return usage;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AuthenticationMethodMfaRecoveryCode
                && equalTo((AuthenticationMethodMfaRecoveryCode) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AuthenticationMethodMfaRecoveryCode other) {
        return confirmed == other.confirmed
                && lastAuthAt.equals(other.lastAuthAt)
                && id.equals(other.id)
                && createdAt.equals(other.createdAt)
                && usage.equals(other.usage);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.confirmed, this.lastAuthAt, this.id, this.createdAt, this.usage);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ConfirmedStage builder() {
        return new Builder();
    }

    public interface ConfirmedStage {
        /**
         * <p>The authentication method status</p>
         */
        IdStage confirmed(boolean confirmed);

        Builder from(AuthenticationMethodMfaRecoveryCode other);
    }

    public interface IdStage {
        /**
         * <p>The unique identifier of the authentication method</p>
         */
        CreatedAtStage id(@NotNull String id);
    }

    public interface CreatedAtStage {
        /**
         * <p>The date and time when the authentication method was created</p>
         */
        _FinalStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface _FinalStage {
        AuthenticationMethodMfaRecoveryCode build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>The date and time when the authentication method was last used</p>
         */
        _FinalStage lastAuthAt(Optional<OffsetDateTime> lastAuthAt);

        _FinalStage lastAuthAt(OffsetDateTime lastAuthAt);

        _FinalStage usage(List<UsageEnum> usage);

        _FinalStage addUsage(UsageEnum usage);

        _FinalStage addAllUsage(List<UsageEnum> usage);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ConfirmedStage, IdStage, CreatedAtStage, _FinalStage {
        private boolean confirmed;

        private String id;

        private OffsetDateTime createdAt;

        private List<UsageEnum> usage = new ArrayList<>();

        private Optional<OffsetDateTime> lastAuthAt = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AuthenticationMethodMfaRecoveryCode other) {
            confirmed(other.getConfirmed());
            lastAuthAt(other.getLastAuthAt());
            id(other.getId());
            createdAt(other.getCreatedAt());
            usage(other.getUsage());
            return this;
        }

        /**
         * <p>The authentication method status</p>
         * <p>The authentication method status</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("confirmed")
        public IdStage confirmed(boolean confirmed) {
            this.confirmed = confirmed;
            return this;
        }

        /**
         * <p>The unique identifier of the authentication method</p>
         * <p>The unique identifier of the authentication method</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public CreatedAtStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The date and time when the authentication method was created</p>
         * <p>The date and time when the authentication method was created</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("created_at")
        public _FinalStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllUsage(List<UsageEnum> usage) {
            if (usage != null) {
                this.usage.addAll(usage);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addUsage(UsageEnum usage) {
            this.usage.add(usage);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "usage", nulls = Nulls.SKIP)
        public _FinalStage usage(List<UsageEnum> usage) {
            this.usage.clear();
            if (usage != null) {
                this.usage.addAll(usage);
            }
            return this;
        }

        /**
         * <p>The date and time when the authentication method was last used</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage lastAuthAt(OffsetDateTime lastAuthAt) {
            this.lastAuthAt = Optional.ofNullable(lastAuthAt);
            return this;
        }

        /**
         * <p>The date and time when the authentication method was last used</p>
         */
        @java.lang.Override
        @JsonSetter(value = "last_auth_at", nulls = Nulls.SKIP)
        public _FinalStage lastAuthAt(Optional<OffsetDateTime> lastAuthAt) {
            this.lastAuthAt = lastAuthAt;
            return this;
        }

        @java.lang.Override
        public AuthenticationMethodMfaRecoveryCode build() {
            return new AuthenticationMethodMfaRecoveryCode(
                    confirmed, lastAuthAt, id, createdAt, usage, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
