/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CompleteConnectedAccountsResponseContent.Builder.class)
public final class CompleteConnectedAccountsResponseContent {
    private final String id;

    private final String connection;

    private final AccessTypeEnum accessType;

    private final Optional<List<String>> scopes;

    private final OffsetDateTime createdAt;

    private final Optional<OffsetDateTime> expiresAt;

    private final Map<String, Object> additionalProperties;

    private CompleteConnectedAccountsResponseContent(
            String id,
            String connection,
            AccessTypeEnum accessType,
            Optional<List<String>> scopes,
            OffsetDateTime createdAt,
            Optional<OffsetDateTime> expiresAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.connection = connection;
        this.accessType = accessType;
        this.scopes = scopes;
        this.createdAt = createdAt;
        this.expiresAt = expiresAt;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique identifier of the connected account
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return The connection name
     */
    @JsonProperty("connection")
    public String getConnection() {
        return connection;
    }

    @JsonProperty("access_type")
    public AccessTypeEnum getAccessType() {
        return accessType;
    }

    /**
     * @return Array of scopes granted
     */
    @JsonProperty("scopes")
    public Optional<List<String>> getScopes() {
        return scopes;
    }

    /**
     * @return ISO date string of when the connected account was created
     */
    @JsonProperty("created_at")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * @return ISO date string of when the refresh token expires (optional)
     */
    @JsonProperty("expires_at")
    public Optional<OffsetDateTime> getExpiresAt() {
        return expiresAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CompleteConnectedAccountsResponseContent
                && equalTo((CompleteConnectedAccountsResponseContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CompleteConnectedAccountsResponseContent other) {
        return id.equals(other.id)
                && connection.equals(other.connection)
                && accessType.equals(other.accessType)
                && scopes.equals(other.scopes)
                && createdAt.equals(other.createdAt)
                && expiresAt.equals(other.expiresAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.connection, this.accessType, this.scopes, this.createdAt, this.expiresAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>The unique identifier of the connected account</p>
         */
        ConnectionStage id(@NotNull String id);

        Builder from(CompleteConnectedAccountsResponseContent other);
    }

    public interface ConnectionStage {
        /**
         * <p>The connection name</p>
         */
        AccessTypeStage connection(@NotNull String connection);
    }

    public interface AccessTypeStage {
        CreatedAtStage accessType(@NotNull AccessTypeEnum accessType);
    }

    public interface CreatedAtStage {
        /**
         * <p>ISO date string of when the connected account was created</p>
         */
        _FinalStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface _FinalStage {
        CompleteConnectedAccountsResponseContent build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Array of scopes granted</p>
         */
        _FinalStage scopes(Optional<List<String>> scopes);

        _FinalStage scopes(List<String> scopes);

        /**
         * <p>ISO date string of when the refresh token expires (optional)</p>
         */
        _FinalStage expiresAt(Optional<OffsetDateTime> expiresAt);

        _FinalStage expiresAt(OffsetDateTime expiresAt);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage, ConnectionStage, AccessTypeStage, CreatedAtStage, _FinalStage {
        private String id;

        private String connection;

        private AccessTypeEnum accessType;

        private OffsetDateTime createdAt;

        private Optional<OffsetDateTime> expiresAt = Optional.empty();

        private Optional<List<String>> scopes = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CompleteConnectedAccountsResponseContent other) {
            id(other.getId());
            connection(other.getConnection());
            accessType(other.getAccessType());
            scopes(other.getScopes());
            createdAt(other.getCreatedAt());
            expiresAt(other.getExpiresAt());
            return this;
        }

        /**
         * <p>The unique identifier of the connected account</p>
         * <p>The unique identifier of the connected account</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public ConnectionStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The connection name</p>
         * <p>The connection name</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("connection")
        public AccessTypeStage connection(@NotNull String connection) {
            this.connection = Objects.requireNonNull(connection, "connection must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("access_type")
        public CreatedAtStage accessType(@NotNull AccessTypeEnum accessType) {
            this.accessType = Objects.requireNonNull(accessType, "accessType must not be null");
            return this;
        }

        /**
         * <p>ISO date string of when the connected account was created</p>
         * <p>ISO date string of when the connected account was created</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("created_at")
        public _FinalStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>ISO date string of when the refresh token expires (optional)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage expiresAt(OffsetDateTime expiresAt) {
            this.expiresAt = Optional.ofNullable(expiresAt);
            return this;
        }

        /**
         * <p>ISO date string of when the refresh token expires (optional)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "expires_at", nulls = Nulls.SKIP)
        public _FinalStage expiresAt(Optional<OffsetDateTime> expiresAt) {
            this.expiresAt = expiresAt;
            return this;
        }

        /**
         * <p>Array of scopes granted</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage scopes(List<String> scopes) {
            this.scopes = Optional.ofNullable(scopes);
            return this;
        }

        /**
         * <p>Array of scopes granted</p>
         */
        @java.lang.Override
        @JsonSetter(value = "scopes", nulls = Nulls.SKIP)
        public _FinalStage scopes(Optional<List<String>> scopes) {
            this.scopes = scopes;
            return this;
        }

        @java.lang.Override
        public CompleteConnectedAccountsResponseContent build() {
            return new CompleteConnectedAccountsResponseContent(
                    id, connection, accessType, scopes, createdAt, expiresAt, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
