/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CompleteConnectedAccountsRequestContent.Builder.class)
public final class CompleteConnectedAccountsRequestContent {
    private final String authSession;

    private final String connectCode;

    private final String redirectUri;

    private final Optional<String> codeVerifier;

    private final Map<String, Object> additionalProperties;

    private CompleteConnectedAccountsRequestContent(
            String authSession,
            String connectCode,
            String redirectUri,
            Optional<String> codeVerifier,
            Map<String, Object> additionalProperties) {
        this.authSession = authSession;
        this.connectCode = connectCode;
        this.redirectUri = redirectUri;
        this.codeVerifier = codeVerifier;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The authentication session identifier
     */
    @JsonProperty("auth_session")
    public String getAuthSession() {
        return authSession;
    }

    /**
     * @return The authorization code returned from the connect flow
     */
    @JsonProperty("connect_code")
    public String getConnectCode() {
        return connectCode;
    }

    /**
     * @return The redirect URI used in the original request
     */
    @JsonProperty("redirect_uri")
    public String getRedirectUri() {
        return redirectUri;
    }

    /**
     * @return The PKCE code verifier
     */
    @JsonProperty("code_verifier")
    public Optional<String> getCodeVerifier() {
        return codeVerifier;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CompleteConnectedAccountsRequestContent
                && equalTo((CompleteConnectedAccountsRequestContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CompleteConnectedAccountsRequestContent other) {
        return authSession.equals(other.authSession)
                && connectCode.equals(other.connectCode)
                && redirectUri.equals(other.redirectUri)
                && codeVerifier.equals(other.codeVerifier);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.authSession, this.connectCode, this.redirectUri, this.codeVerifier);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AuthSessionStage builder() {
        return new Builder();
    }

    public interface AuthSessionStage {
        /**
         * <p>The authentication session identifier</p>
         */
        ConnectCodeStage authSession(@NotNull String authSession);

        Builder from(CompleteConnectedAccountsRequestContent other);
    }

    public interface ConnectCodeStage {
        /**
         * <p>The authorization code returned from the connect flow</p>
         */
        RedirectUriStage connectCode(@NotNull String connectCode);
    }

    public interface RedirectUriStage {
        /**
         * <p>The redirect URI used in the original request</p>
         */
        _FinalStage redirectUri(@NotNull String redirectUri);
    }

    public interface _FinalStage {
        CompleteConnectedAccountsRequestContent build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>The PKCE code verifier</p>
         */
        _FinalStage codeVerifier(Optional<String> codeVerifier);

        _FinalStage codeVerifier(String codeVerifier);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AuthSessionStage, ConnectCodeStage, RedirectUriStage, _FinalStage {
        private String authSession;

        private String connectCode;

        private String redirectUri;

        private Optional<String> codeVerifier = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CompleteConnectedAccountsRequestContent other) {
            authSession(other.getAuthSession());
            connectCode(other.getConnectCode());
            redirectUri(other.getRedirectUri());
            codeVerifier(other.getCodeVerifier());
            return this;
        }

        /**
         * <p>The authentication session identifier</p>
         * <p>The authentication session identifier</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("auth_session")
        public ConnectCodeStage authSession(@NotNull String authSession) {
            this.authSession = Objects.requireNonNull(authSession, "authSession must not be null");
            return this;
        }

        /**
         * <p>The authorization code returned from the connect flow</p>
         * <p>The authorization code returned from the connect flow</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("connect_code")
        public RedirectUriStage connectCode(@NotNull String connectCode) {
            this.connectCode = Objects.requireNonNull(connectCode, "connectCode must not be null");
            return this;
        }

        /**
         * <p>The redirect URI used in the original request</p>
         * <p>The redirect URI used in the original request</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("redirect_uri")
        public _FinalStage redirectUri(@NotNull String redirectUri) {
            this.redirectUri = Objects.requireNonNull(redirectUri, "redirectUri must not be null");
            return this;
        }

        /**
         * <p>The PKCE code verifier</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage codeVerifier(String codeVerifier) {
            this.codeVerifier = Optional.ofNullable(codeVerifier);
            return this;
        }

        /**
         * <p>The PKCE code verifier</p>
         */
        @java.lang.Override
        @JsonSetter(value = "code_verifier", nulls = Nulls.SKIP)
        public _FinalStage codeVerifier(Optional<String> codeVerifier) {
            this.codeVerifier = codeVerifier;
            return this;
        }

        @java.lang.Override
        public CompleteConnectedAccountsRequestContent build() {
            return new CompleteConnectedAccountsRequestContent(
                    authSession, connectCode, redirectUri, codeVerifier, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
