/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConnectedAccountConnection.Builder.class)
public final class ConnectedAccountConnection {
    private final String name;

    private final String strategy;

    private final Optional<List<String>> scopes;

    private final Map<String, Object> additionalProperties;

    private ConnectedAccountConnection(
            String name, String strategy, Optional<List<String>> scopes, Map<String, Object> additionalProperties) {
        this.name = name;
        this.strategy = strategy;
        this.scopes = scopes;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The name of the connection.
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return The strategy used by the connection (e.g., 'oauth2', 'oidc').
     */
    @JsonProperty("strategy")
    public String getStrategy() {
        return strategy;
    }

    /**
     * @return The available scopes for this connection.
     */
    @JsonProperty("scopes")
    public Optional<List<String>> getScopes() {
        return scopes;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConnectedAccountConnection && equalTo((ConnectedAccountConnection) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConnectedAccountConnection other) {
        return name.equals(other.name) && strategy.equals(other.strategy) && scopes.equals(other.scopes);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.strategy, this.scopes);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        /**
         * <p>The name of the connection.</p>
         */
        StrategyStage name(@NotNull String name);

        Builder from(ConnectedAccountConnection other);
    }

    public interface StrategyStage {
        /**
         * <p>The strategy used by the connection (e.g., 'oauth2', 'oidc').</p>
         */
        _FinalStage strategy(@NotNull String strategy);
    }

    public interface _FinalStage {
        ConnectedAccountConnection build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>The available scopes for this connection.</p>
         */
        _FinalStage scopes(Optional<List<String>> scopes);

        _FinalStage scopes(List<String> scopes);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, StrategyStage, _FinalStage {
        private String name;

        private String strategy;

        private Optional<List<String>> scopes = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ConnectedAccountConnection other) {
            name(other.getName());
            strategy(other.getStrategy());
            scopes(other.getScopes());
            return this;
        }

        /**
         * <p>The name of the connection.</p>
         * <p>The name of the connection.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public StrategyStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>The strategy used by the connection (e.g., 'oauth2', 'oidc').</p>
         * <p>The strategy used by the connection (e.g., 'oauth2', 'oidc').</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("strategy")
        public _FinalStage strategy(@NotNull String strategy) {
            this.strategy = Objects.requireNonNull(strategy, "strategy must not be null");
            return this;
        }

        /**
         * <p>The available scopes for this connection.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage scopes(List<String> scopes) {
            this.scopes = Optional.ofNullable(scopes);
            return this;
        }

        /**
         * <p>The available scopes for this connection.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "scopes", nulls = Nulls.SKIP)
        public _FinalStage scopes(Optional<List<String>> scopes) {
            this.scopes = scopes;
            return this;
        }

        @java.lang.Override
        public ConnectedAccountConnection build() {
            return new ConnectedAccountConnection(name, strategy, scopes, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
