/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConnectedAccount.Builder.class)
public final class ConnectedAccount {
    private final String id;

    private final String connection;

    private final ConnectedAccountAccessTypeEnum accessType;

    private final List<String> scopes;

    private final OffsetDateTime createdAt;

    private final Optional<OffsetDateTime> expiresAt;

    private final Optional<String> orgId;

    private final Map<String, Object> additionalProperties;

    private ConnectedAccount(
            String id,
            String connection,
            ConnectedAccountAccessTypeEnum accessType,
            List<String> scopes,
            OffsetDateTime createdAt,
            Optional<OffsetDateTime> expiresAt,
            Optional<String> orgId,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.connection = connection;
        this.accessType = accessType;
        this.scopes = scopes;
        this.createdAt = createdAt;
        this.expiresAt = expiresAt;
        this.orgId = orgId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique identifier for the connected account.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return The name of the connection associated with the account.
     */
    @JsonProperty("connection")
    public String getConnection() {
        return connection;
    }

    @JsonProperty("access_type")
    public ConnectedAccountAccessTypeEnum getAccessType() {
        return accessType;
    }

    /**
     * @return The scopes granted for this connected account.
     */
    @JsonProperty("scopes")
    public List<String> getScopes() {
        return scopes;
    }

    /**
     * @return ISO 8601 timestamp when the connected account was created.
     */
    @JsonProperty("created_at")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * @return ISO 8601 timestamp when the connected account expires.
     */
    @JsonProperty("expires_at")
    public Optional<OffsetDateTime> getExpiresAt() {
        return expiresAt;
    }

    /**
     * @return The organization ID this connected account is scoped to. Only present for accounts bound to an organization.
     */
    @JsonProperty("org_id")
    public Optional<String> getOrgId() {
        return orgId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConnectedAccount && equalTo((ConnectedAccount) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConnectedAccount other) {
        return id.equals(other.id)
                && connection.equals(other.connection)
                && accessType.equals(other.accessType)
                && scopes.equals(other.scopes)
                && createdAt.equals(other.createdAt)
                && expiresAt.equals(other.expiresAt)
                && orgId.equals(other.orgId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id, this.connection, this.accessType, this.scopes, this.createdAt, this.expiresAt, this.orgId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>The unique identifier for the connected account.</p>
         */
        ConnectionStage id(@NotNull String id);

        Builder from(ConnectedAccount other);
    }

    public interface ConnectionStage {
        /**
         * <p>The name of the connection associated with the account.</p>
         */
        AccessTypeStage connection(@NotNull String connection);
    }

    public interface AccessTypeStage {
        CreatedAtStage accessType(@NotNull ConnectedAccountAccessTypeEnum accessType);
    }

    public interface CreatedAtStage {
        /**
         * <p>ISO 8601 timestamp when the connected account was created.</p>
         */
        _FinalStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface _FinalStage {
        ConnectedAccount build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>The scopes granted for this connected account.</p>
         */
        _FinalStage scopes(List<String> scopes);

        _FinalStage addScopes(String scopes);

        _FinalStage addAllScopes(List<String> scopes);

        /**
         * <p>ISO 8601 timestamp when the connected account expires.</p>
         */
        _FinalStage expiresAt(Optional<OffsetDateTime> expiresAt);

        _FinalStage expiresAt(OffsetDateTime expiresAt);

        /**
         * <p>The organization ID this connected account is scoped to. Only present for accounts bound to an organization.</p>
         */
        _FinalStage orgId(Optional<String> orgId);

        _FinalStage orgId(String orgId);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage, ConnectionStage, AccessTypeStage, CreatedAtStage, _FinalStage {
        private String id;

        private String connection;

        private ConnectedAccountAccessTypeEnum accessType;

        private OffsetDateTime createdAt;

        private Optional<String> orgId = Optional.empty();

        private Optional<OffsetDateTime> expiresAt = Optional.empty();

        private List<String> scopes = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ConnectedAccount other) {
            id(other.getId());
            connection(other.getConnection());
            accessType(other.getAccessType());
            scopes(other.getScopes());
            createdAt(other.getCreatedAt());
            expiresAt(other.getExpiresAt());
            orgId(other.getOrgId());
            return this;
        }

        /**
         * <p>The unique identifier for the connected account.</p>
         * <p>The unique identifier for the connected account.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public ConnectionStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The name of the connection associated with the account.</p>
         * <p>The name of the connection associated with the account.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("connection")
        public AccessTypeStage connection(@NotNull String connection) {
            this.connection = Objects.requireNonNull(connection, "connection must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("access_type")
        public CreatedAtStage accessType(@NotNull ConnectedAccountAccessTypeEnum accessType) {
            this.accessType = Objects.requireNonNull(accessType, "accessType must not be null");
            return this;
        }

        /**
         * <p>ISO 8601 timestamp when the connected account was created.</p>
         * <p>ISO 8601 timestamp when the connected account was created.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("created_at")
        public _FinalStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>The organization ID this connected account is scoped to. Only present for accounts bound to an organization.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage orgId(String orgId) {
            this.orgId = Optional.ofNullable(orgId);
            return this;
        }

        /**
         * <p>The organization ID this connected account is scoped to. Only present for accounts bound to an organization.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "org_id", nulls = Nulls.SKIP)
        public _FinalStage orgId(Optional<String> orgId) {
            this.orgId = orgId;
            return this;
        }

        /**
         * <p>ISO 8601 timestamp when the connected account expires.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage expiresAt(OffsetDateTime expiresAt) {
            this.expiresAt = Optional.ofNullable(expiresAt);
            return this;
        }

        /**
         * <p>ISO 8601 timestamp when the connected account expires.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "expires_at", nulls = Nulls.SKIP)
        public _FinalStage expiresAt(Optional<OffsetDateTime> expiresAt) {
            this.expiresAt = expiresAt;
            return this;
        }

        /**
         * <p>The scopes granted for this connected account.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllScopes(List<String> scopes) {
            if (scopes != null) {
                this.scopes.addAll(scopes);
            }
            return this;
        }

        /**
         * <p>The scopes granted for this connected account.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addScopes(String scopes) {
            this.scopes.add(scopes);
            return this;
        }

        /**
         * <p>The scopes granted for this connected account.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "scopes", nulls = Nulls.SKIP)
        public _FinalStage scopes(List<String> scopes) {
            this.scopes.clear();
            if (scopes != null) {
                this.scopes.addAll(scopes);
            }
            return this;
        }

        @java.lang.Override
        public ConnectedAccount build() {
            return new ConnectedAccount(
                    id, connection, accessType, scopes, createdAt, expiresAt, orgId, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
