/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CreateConnectedAccountsRequestContentCodeChallengeMethod {
    public static final CreateConnectedAccountsRequestContentCodeChallengeMethod S256 =
            new CreateConnectedAccountsRequestContentCodeChallengeMethod(Value.S256, "S256");

    private final Value value;

    private final String string;

    CreateConnectedAccountsRequestContentCodeChallengeMethod(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CreateConnectedAccountsRequestContentCodeChallengeMethod
                        && this.string.equals(
                                ((CreateConnectedAccountsRequestContentCodeChallengeMethod) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case S256:
                return visitor.visitS256();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CreateConnectedAccountsRequestContentCodeChallengeMethod valueOf(String value) {
        switch (value) {
            case "S256":
                return S256;
            default:
                return new CreateConnectedAccountsRequestContentCodeChallengeMethod(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        S256,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitS256();

        T visitUnknown(String unknownType);
    }
}
