/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateConnectedAccountsRequestContent.Builder.class)
public final class CreateConnectedAccountsRequestContent {
    private final String connection;

    private final String redirectUri;

    private final Optional<String> state;

    private final Optional<String> codeChallenge;

    private final Optional<CreateConnectedAccountsRequestContentCodeChallengeMethod> codeChallengeMethod;

    private final Optional<List<String>> scopes;

    private final Optional<AuthorizationParams> authorizationParams;

    private final Map<String, Object> additionalProperties;

    private CreateConnectedAccountsRequestContent(
            String connection,
            String redirectUri,
            Optional<String> state,
            Optional<String> codeChallenge,
            Optional<CreateConnectedAccountsRequestContentCodeChallengeMethod> codeChallengeMethod,
            Optional<List<String>> scopes,
            Optional<AuthorizationParams> authorizationParams,
            Map<String, Object> additionalProperties) {
        this.connection = connection;
        this.redirectUri = redirectUri;
        this.state = state;
        this.codeChallenge = codeChallenge;
        this.codeChallengeMethod = codeChallengeMethod;
        this.scopes = scopes;
        this.authorizationParams = authorizationParams;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The name of the connection to link the account with (e.g., 'google-oauth2', 'facebook').
     */
    @JsonProperty("connection")
    public String getConnection() {
        return connection;
    }

    /**
     * @return The URI to redirect to after the connection process completes.
     */
    @JsonProperty("redirect_uri")
    public String getRedirectUri() {
        return redirectUri;
    }

    /**
     * @return An opaque value used to maintain state between the request and callback.
     */
    @JsonProperty("state")
    public Optional<String> getState() {
        return state;
    }

    /**
     * @return The PKCE code challenge derived from the code verifier.
     */
    @JsonProperty("code_challenge")
    public Optional<String> getCodeChallenge() {
        return codeChallenge;
    }

    /**
     * @return The method used to derive the code challenge. Required when code_challenge is provided.
     */
    @JsonProperty("code_challenge_method")
    public Optional<CreateConnectedAccountsRequestContentCodeChallengeMethod> getCodeChallengeMethod() {
        return codeChallengeMethod;
    }

    /**
     * @return Defines the permissions that the client requests from the Identity Provider. Must include the standard scopes used to identify the user (e.g. 'openid', 'email', 'profile'), the scope required to obtain refresh tokens if needed (e.g. 'offline_access'), and any custom scopes the client needs to access protected resources.
     */
    @JsonProperty("scopes")
    public Optional<List<String>> getScopes() {
        return scopes;
    }

    @JsonProperty("authorization_params")
    public Optional<AuthorizationParams> getAuthorizationParams() {
        return authorizationParams;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateConnectedAccountsRequestContent
                && equalTo((CreateConnectedAccountsRequestContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateConnectedAccountsRequestContent other) {
        return connection.equals(other.connection)
                && redirectUri.equals(other.redirectUri)
                && state.equals(other.state)
                && codeChallenge.equals(other.codeChallenge)
                && codeChallengeMethod.equals(other.codeChallengeMethod)
                && scopes.equals(other.scopes)
                && authorizationParams.equals(other.authorizationParams);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.connection,
                this.redirectUri,
                this.state,
                this.codeChallenge,
                this.codeChallengeMethod,
                this.scopes,
                this.authorizationParams);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ConnectionStage builder() {
        return new Builder();
    }

    public interface ConnectionStage {
        /**
         * <p>The name of the connection to link the account with (e.g., 'google-oauth2', 'facebook').</p>
         */
        RedirectUriStage connection(@NotNull String connection);

        Builder from(CreateConnectedAccountsRequestContent other);
    }

    public interface RedirectUriStage {
        /**
         * <p>The URI to redirect to after the connection process completes.</p>
         */
        _FinalStage redirectUri(@NotNull String redirectUri);
    }

    public interface _FinalStage {
        CreateConnectedAccountsRequestContent build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>An opaque value used to maintain state between the request and callback.</p>
         */
        _FinalStage state(Optional<String> state);

        _FinalStage state(String state);

        /**
         * <p>The PKCE code challenge derived from the code verifier.</p>
         */
        _FinalStage codeChallenge(Optional<String> codeChallenge);

        _FinalStage codeChallenge(String codeChallenge);

        /**
         * <p>The method used to derive the code challenge. Required when code_challenge is provided.</p>
         */
        _FinalStage codeChallengeMethod(
                Optional<CreateConnectedAccountsRequestContentCodeChallengeMethod> codeChallengeMethod);

        _FinalStage codeChallengeMethod(CreateConnectedAccountsRequestContentCodeChallengeMethod codeChallengeMethod);

        /**
         * <p>Defines the permissions that the client requests from the Identity Provider. Must include the standard scopes used to identify the user (e.g. 'openid', 'email', 'profile'), the scope required to obtain refresh tokens if needed (e.g. 'offline_access'), and any custom scopes the client needs to access protected resources.</p>
         */
        _FinalStage scopes(Optional<List<String>> scopes);

        _FinalStage scopes(List<String> scopes);

        _FinalStage authorizationParams(Optional<AuthorizationParams> authorizationParams);

        _FinalStage authorizationParams(AuthorizationParams authorizationParams);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ConnectionStage, RedirectUriStage, _FinalStage {
        private String connection;

        private String redirectUri;

        private Optional<AuthorizationParams> authorizationParams = Optional.empty();

        private Optional<List<String>> scopes = Optional.empty();

        private Optional<CreateConnectedAccountsRequestContentCodeChallengeMethod> codeChallengeMethod =
                Optional.empty();

        private Optional<String> codeChallenge = Optional.empty();

        private Optional<String> state = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateConnectedAccountsRequestContent other) {
            connection(other.getConnection());
            redirectUri(other.getRedirectUri());
            state(other.getState());
            codeChallenge(other.getCodeChallenge());
            codeChallengeMethod(other.getCodeChallengeMethod());
            scopes(other.getScopes());
            authorizationParams(other.getAuthorizationParams());
            return this;
        }

        /**
         * <p>The name of the connection to link the account with (e.g., 'google-oauth2', 'facebook').</p>
         * <p>The name of the connection to link the account with (e.g., 'google-oauth2', 'facebook').</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("connection")
        public RedirectUriStage connection(@NotNull String connection) {
            this.connection = Objects.requireNonNull(connection, "connection must not be null");
            return this;
        }

        /**
         * <p>The URI to redirect to after the connection process completes.</p>
         * <p>The URI to redirect to after the connection process completes.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("redirect_uri")
        public _FinalStage redirectUri(@NotNull String redirectUri) {
            this.redirectUri = Objects.requireNonNull(redirectUri, "redirectUri must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage authorizationParams(AuthorizationParams authorizationParams) {
            this.authorizationParams = Optional.ofNullable(authorizationParams);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "authorization_params", nulls = Nulls.SKIP)
        public _FinalStage authorizationParams(Optional<AuthorizationParams> authorizationParams) {
            this.authorizationParams = authorizationParams;
            return this;
        }

        /**
         * <p>Defines the permissions that the client requests from the Identity Provider. Must include the standard scopes used to identify the user (e.g. 'openid', 'email', 'profile'), the scope required to obtain refresh tokens if needed (e.g. 'offline_access'), and any custom scopes the client needs to access protected resources.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage scopes(List<String> scopes) {
            this.scopes = Optional.ofNullable(scopes);
            return this;
        }

        /**
         * <p>Defines the permissions that the client requests from the Identity Provider. Must include the standard scopes used to identify the user (e.g. 'openid', 'email', 'profile'), the scope required to obtain refresh tokens if needed (e.g. 'offline_access'), and any custom scopes the client needs to access protected resources.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "scopes", nulls = Nulls.SKIP)
        public _FinalStage scopes(Optional<List<String>> scopes) {
            this.scopes = scopes;
            return this;
        }

        /**
         * <p>The method used to derive the code challenge. Required when code_challenge is provided.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage codeChallengeMethod(
                CreateConnectedAccountsRequestContentCodeChallengeMethod codeChallengeMethod) {
            this.codeChallengeMethod = Optional.ofNullable(codeChallengeMethod);
            return this;
        }

        /**
         * <p>The method used to derive the code challenge. Required when code_challenge is provided.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "code_challenge_method", nulls = Nulls.SKIP)
        public _FinalStage codeChallengeMethod(
                Optional<CreateConnectedAccountsRequestContentCodeChallengeMethod> codeChallengeMethod) {
            this.codeChallengeMethod = codeChallengeMethod;
            return this;
        }

        /**
         * <p>The PKCE code challenge derived from the code verifier.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage codeChallenge(String codeChallenge) {
            this.codeChallenge = Optional.ofNullable(codeChallenge);
            return this;
        }

        /**
         * <p>The PKCE code challenge derived from the code verifier.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "code_challenge", nulls = Nulls.SKIP)
        public _FinalStage codeChallenge(Optional<String> codeChallenge) {
            this.codeChallenge = codeChallenge;
            return this;
        }

        /**
         * <p>An opaque value used to maintain state between the request and callback.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage state(String state) {
            this.state = Optional.ofNullable(state);
            return this;
        }

        /**
         * <p>An opaque value used to maintain state between the request and callback.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "state", nulls = Nulls.SKIP)
        public _FinalStage state(Optional<String> state) {
            this.state = state;
            return this;
        }

        @java.lang.Override
        public CreateConnectedAccountsRequestContent build() {
            return new CreateConnectedAccountsRequestContent(
                    connection,
                    redirectUri,
                    state,
                    codeChallenge,
                    codeChallengeMethod,
                    scopes,
                    authorizationParams,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
