/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

public final class CreateAuthenticationMethodRequestContent {
    private final Value value;

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    private CreateAuthenticationMethodRequestContent(Value value) {
        this.value = value;
    }

    public <T> T visit(Visitor<T> visitor) {
        return value.visit(visitor);
    }

    public static CreateAuthenticationMethodRequestContent passkey(CreatePasskeyAuthenticationMethod value) {
        return new CreateAuthenticationMethodRequestContent(new PasskeyValue(value));
    }

    public static CreateAuthenticationMethodRequestContent totp(CreateTotpAuthenticationMethod value) {
        return new CreateAuthenticationMethodRequestContent(new TotpValue(value));
    }

    public static CreateAuthenticationMethodRequestContent pushNotification(
            CreatePushNotificationAuthenticationMethod value) {
        return new CreateAuthenticationMethodRequestContent(new PushNotificationValue(value));
    }

    public static CreateAuthenticationMethodRequestContent recoveryCode(CreateRecoveryCodeAuthenticationMethod value) {
        return new CreateAuthenticationMethodRequestContent(new RecoveryCodeValue(value));
    }

    public static CreateAuthenticationMethodRequestContent email(CreateEmailAuthenticationMethod value) {
        return new CreateAuthenticationMethodRequestContent(new EmailValue(value));
    }

    public static CreateAuthenticationMethodRequestContent phone(CreatePhoneAuthenticationMethod value) {
        return new CreateAuthenticationMethodRequestContent(new PhoneValue(value));
    }

    public static CreateAuthenticationMethodRequestContent password(CreatePasswordAuthenticationMethod value) {
        return new CreateAuthenticationMethodRequestContent(new PasswordValue(value));
    }

    public boolean isPasskey() {
        return value instanceof PasskeyValue;
    }

    public boolean isTotp() {
        return value instanceof TotpValue;
    }

    public boolean isPushNotification() {
        return value instanceof PushNotificationValue;
    }

    public boolean isRecoveryCode() {
        return value instanceof RecoveryCodeValue;
    }

    public boolean isEmail() {
        return value instanceof EmailValue;
    }

    public boolean isPhone() {
        return value instanceof PhoneValue;
    }

    public boolean isPassword() {
        return value instanceof PasswordValue;
    }

    public boolean _isUnknown() {
        return value instanceof _UnknownValue;
    }

    public Optional<CreatePasskeyAuthenticationMethod> getPasskey() {
        if (isPasskey()) {
            return Optional.of(((PasskeyValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateTotpAuthenticationMethod> getTotp() {
        if (isTotp()) {
            return Optional.of(((TotpValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreatePushNotificationAuthenticationMethod> getPushNotification() {
        if (isPushNotification()) {
            return Optional.of(((PushNotificationValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateRecoveryCodeAuthenticationMethod> getRecoveryCode() {
        if (isRecoveryCode()) {
            return Optional.of(((RecoveryCodeValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreateEmailAuthenticationMethod> getEmail() {
        if (isEmail()) {
            return Optional.of(((EmailValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreatePhoneAuthenticationMethod> getPhone() {
        if (isPhone()) {
            return Optional.of(((PhoneValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreatePasswordAuthenticationMethod> getPassword() {
        if (isPassword()) {
            return Optional.of(((PasswordValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Object> _getUnknown() {
        if (_isUnknown()) {
            return Optional.of(((_UnknownValue) value).value);
        }
        return Optional.empty();
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateAuthenticationMethodRequestContent
                && value.equals(((CreateAuthenticationMethodRequestContent) other).value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public String toString() {
        return value.toString();
    }

    @JsonValue
    private Value getValue() {
        return this.value;
    }

    public interface Visitor<T> {
        T visitPasskey(CreatePasskeyAuthenticationMethod passkey);

        T visitTotp(CreateTotpAuthenticationMethod totp);

        T visitPushNotification(CreatePushNotificationAuthenticationMethod pushNotification);

        T visitRecoveryCode(CreateRecoveryCodeAuthenticationMethod recoveryCode);

        T visitEmail(CreateEmailAuthenticationMethod email);

        T visitPhone(CreatePhoneAuthenticationMethod phone);

        T visitPassword(CreatePasswordAuthenticationMethod password);

        T _visitUnknown(Object unknownType);
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = true, defaultImpl = _UnknownValue.class)
    @JsonSubTypes({
        @JsonSubTypes.Type(PasskeyValue.class),
        @JsonSubTypes.Type(TotpValue.class),
        @JsonSubTypes.Type(PushNotificationValue.class),
        @JsonSubTypes.Type(RecoveryCodeValue.class),
        @JsonSubTypes.Type(EmailValue.class),
        @JsonSubTypes.Type(PhoneValue.class),
        @JsonSubTypes.Type(PasswordValue.class)
    })
    @JsonIgnoreProperties(ignoreUnknown = true)
    private interface Value {
        <T> T visit(Visitor<T> visitor);
    }

    @JsonTypeName("passkey")
    @JsonIgnoreProperties("type")
    private static final class PasskeyValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private CreatePasskeyAuthenticationMethod value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private PasskeyValue() {}

        private PasskeyValue(CreatePasskeyAuthenticationMethod value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitPasskey(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof PasskeyValue && equalTo((PasskeyValue) other);
        }

        private boolean equalTo(PasskeyValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "CreateAuthenticationMethodRequestContent{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("totp")
    @JsonIgnoreProperties("type")
    private static final class TotpValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private CreateTotpAuthenticationMethod value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private TotpValue() {}

        private TotpValue(CreateTotpAuthenticationMethod value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitTotp(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof TotpValue && equalTo((TotpValue) other);
        }

        private boolean equalTo(TotpValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "CreateAuthenticationMethodRequestContent{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("push-notification")
    @JsonIgnoreProperties("type")
    private static final class PushNotificationValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private CreatePushNotificationAuthenticationMethod value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private PushNotificationValue() {}

        private PushNotificationValue(CreatePushNotificationAuthenticationMethod value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitPushNotification(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof PushNotificationValue && equalTo((PushNotificationValue) other);
        }

        private boolean equalTo(PushNotificationValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "CreateAuthenticationMethodRequestContent{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("recovery-code")
    @JsonIgnoreProperties("type")
    private static final class RecoveryCodeValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private CreateRecoveryCodeAuthenticationMethod value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private RecoveryCodeValue() {}

        private RecoveryCodeValue(CreateRecoveryCodeAuthenticationMethod value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitRecoveryCode(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof RecoveryCodeValue && equalTo((RecoveryCodeValue) other);
        }

        private boolean equalTo(RecoveryCodeValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "CreateAuthenticationMethodRequestContent{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("email")
    @JsonIgnoreProperties("type")
    private static final class EmailValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private CreateEmailAuthenticationMethod value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private EmailValue() {}

        private EmailValue(CreateEmailAuthenticationMethod value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitEmail(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof EmailValue && equalTo((EmailValue) other);
        }

        private boolean equalTo(EmailValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "CreateAuthenticationMethodRequestContent{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("phone")
    @JsonIgnoreProperties("type")
    private static final class PhoneValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private CreatePhoneAuthenticationMethod value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private PhoneValue() {}

        private PhoneValue(CreatePhoneAuthenticationMethod value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitPhone(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof PhoneValue && equalTo((PhoneValue) other);
        }

        private boolean equalTo(PhoneValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "CreateAuthenticationMethodRequestContent{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("password")
    @JsonIgnoreProperties("type")
    private static final class PasswordValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private CreatePasswordAuthenticationMethod value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private PasswordValue() {}

        private PasswordValue(CreatePasswordAuthenticationMethod value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitPassword(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof PasswordValue && equalTo((PasswordValue) other);
        }

        private boolean equalTo(PasswordValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "CreateAuthenticationMethodRequestContent{" + "value: " + value + "}";
        }
    }

    @JsonIgnoreProperties("type")
    private static final class _UnknownValue implements Value {
        private String type;

        @JsonValue
        private Object value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private _UnknownValue(@JsonProperty("value") Object value) {}

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor._visitUnknown(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof _UnknownValue && equalTo((_UnknownValue) other);
        }

        private boolean equalTo(_UnknownValue other) {
            return type.equals(other.type) && value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.type, this.value);
        }

        @java.lang.Override
        public String toString() {
            return "CreateAuthenticationMethodRequestContent{" + "type: " + type + ", value: " + value + "}";
        }
    }
}
