/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import java.io.IOException;
import java.util.Map;
import java.util.Objects;

@JsonDeserialize(using = CreateAuthenticationMethodResponseContent.Deserializer.class)
public final class CreateAuthenticationMethodResponseContent {
    private final Object value;

    private final int type;

    private CreateAuthenticationMethodResponseContent(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((PasskeyCreationResponse) this.value);
        } else if (this.type == 1) {
            return visitor.visit((WebAuthnCreationResponse) this.value);
        } else if (this.type == 2) {
            return visitor.visit((MfaBaseCreationResponse) this.value);
        } else if (this.type == 3) {
            return visitor.visit((QrCodeCreationResponse) this.value);
        } else if (this.type == 4) {
            return visitor.visit((RecoveryCodeCreationResponse) this.value);
        } else if (this.type == 5) {
            return visitor.visit((PasswordCreationResponse) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateAuthenticationMethodResponseContent
                && equalTo((CreateAuthenticationMethodResponseContent) other);
    }

    private boolean equalTo(CreateAuthenticationMethodResponseContent other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static CreateAuthenticationMethodResponseContent of(PasskeyCreationResponse value) {
        return new CreateAuthenticationMethodResponseContent(value, 0);
    }

    public static CreateAuthenticationMethodResponseContent of(WebAuthnCreationResponse value) {
        return new CreateAuthenticationMethodResponseContent(value, 1);
    }

    public static CreateAuthenticationMethodResponseContent of(MfaBaseCreationResponse value) {
        return new CreateAuthenticationMethodResponseContent(value, 2);
    }

    public static CreateAuthenticationMethodResponseContent of(QrCodeCreationResponse value) {
        return new CreateAuthenticationMethodResponseContent(value, 3);
    }

    public static CreateAuthenticationMethodResponseContent of(RecoveryCodeCreationResponse value) {
        return new CreateAuthenticationMethodResponseContent(value, 4);
    }

    public static CreateAuthenticationMethodResponseContent of(PasswordCreationResponse value) {
        return new CreateAuthenticationMethodResponseContent(value, 5);
    }

    public interface Visitor<T> {
        T visit(PasskeyCreationResponse value);

        T visit(WebAuthnCreationResponse value);

        T visit(MfaBaseCreationResponse value);

        T visit(QrCodeCreationResponse value);

        T visit(RecoveryCodeCreationResponse value);

        T visit(PasswordCreationResponse value);
    }

    static final class Deserializer extends StdDeserializer<CreateAuthenticationMethodResponseContent> {
        Deserializer() {
            super(CreateAuthenticationMethodResponseContent.class);
        }

        @java.lang.Override
        public CreateAuthenticationMethodResponseContent deserialize(JsonParser p, DeserializationContext context)
                throws IOException {
            Object value = p.readValueAs(Object.class);
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("auth_session")
                    && ((Map<?, ?>) value).containsKey("authn_params_public_key")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, PasskeyCreationResponse.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("authn_params_public_key")
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("auth_session")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, WebAuthnCreationResponse.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("auth_session")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, MfaBaseCreationResponse.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("barcode_uri")
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("auth_session")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, QrCodeCreationResponse.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("recovery_code")
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("auth_session")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, RecoveryCodeCreationResponse.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("policy")
                    && ((Map<?, ?>) value).containsKey("auth_session")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, PasswordCreationResponse.class));
                } catch (RuntimeException e) {
                }
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
