/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateConnectedAccountsResponseContent.Builder.class)
public final class CreateConnectedAccountsResponseContent {
    private final String connectUri;

    private final String authSession;

    private final ConnectParams connectParams;

    private final int expiresIn;

    private final Map<String, Object> additionalProperties;

    private CreateConnectedAccountsResponseContent(
            String connectUri,
            String authSession,
            ConnectParams connectParams,
            int expiresIn,
            Map<String, Object> additionalProperties) {
        this.connectUri = connectUri;
        this.authSession = authSession;
        this.connectParams = connectParams;
        this.expiresIn = expiresIn;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The base URI to initiate the account connection flow.
     */
    @JsonProperty("connect_uri")
    public String getConnectUri() {
        return connectUri;
    }

    /**
     * @return The authentication session identifier.
     */
    @JsonProperty("auth_session")
    public String getAuthSession() {
        return authSession;
    }

    @JsonProperty("connect_params")
    public ConnectParams getConnectParams() {
        return connectParams;
    }

    /**
     * @return The number of seconds until the ticket expires.
     */
    @JsonProperty("expires_in")
    public int getExpiresIn() {
        return expiresIn;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateConnectedAccountsResponseContent
                && equalTo((CreateConnectedAccountsResponseContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateConnectedAccountsResponseContent other) {
        return connectUri.equals(other.connectUri)
                && authSession.equals(other.authSession)
                && connectParams.equals(other.connectParams)
                && expiresIn == other.expiresIn;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.connectUri, this.authSession, this.connectParams, this.expiresIn);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ConnectUriStage builder() {
        return new Builder();
    }

    public interface ConnectUriStage {
        /**
         * <p>The base URI to initiate the account connection flow.</p>
         */
        AuthSessionStage connectUri(@NotNull String connectUri);

        Builder from(CreateConnectedAccountsResponseContent other);
    }

    public interface AuthSessionStage {
        /**
         * <p>The authentication session identifier.</p>
         */
        ConnectParamsStage authSession(@NotNull String authSession);
    }

    public interface ConnectParamsStage {
        ExpiresInStage connectParams(@NotNull ConnectParams connectParams);
    }

    public interface ExpiresInStage {
        /**
         * <p>The number of seconds until the ticket expires.</p>
         */
        _FinalStage expiresIn(int expiresIn);
    }

    public interface _FinalStage {
        CreateConnectedAccountsResponseContent build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ConnectUriStage, AuthSessionStage, ConnectParamsStage, ExpiresInStage, _FinalStage {
        private String connectUri;

        private String authSession;

        private ConnectParams connectParams;

        private int expiresIn;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateConnectedAccountsResponseContent other) {
            connectUri(other.getConnectUri());
            authSession(other.getAuthSession());
            connectParams(other.getConnectParams());
            expiresIn(other.getExpiresIn());
            return this;
        }

        /**
         * <p>The base URI to initiate the account connection flow.</p>
         * <p>The base URI to initiate the account connection flow.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("connect_uri")
        public AuthSessionStage connectUri(@NotNull String connectUri) {
            this.connectUri = Objects.requireNonNull(connectUri, "connectUri must not be null");
            return this;
        }

        /**
         * <p>The authentication session identifier.</p>
         * <p>The authentication session identifier.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("auth_session")
        public ConnectParamsStage authSession(@NotNull String authSession) {
            this.authSession = Objects.requireNonNull(authSession, "authSession must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("connect_params")
        public ExpiresInStage connectParams(@NotNull ConnectParams connectParams) {
            this.connectParams = Objects.requireNonNull(connectParams, "connectParams must not be null");
            return this;
        }

        /**
         * <p>The number of seconds until the ticket expires.</p>
         * <p>The number of seconds until the ticket expires.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("expires_in")
        public _FinalStage expiresIn(int expiresIn) {
            this.expiresIn = expiresIn;
            return this;
        }

        @java.lang.Override
        public CreateConnectedAccountsResponseContent build() {
            return new CreateConnectedAccountsResponseContent(
                    connectUri, authSession, connectParams, expiresIn, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
