/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DisplayEnum {
    public static final DisplayEnum WAP = new DisplayEnum(Value.WAP, "wap");

    public static final DisplayEnum PAGE = new DisplayEnum(Value.PAGE, "page");

    public static final DisplayEnum POPUP = new DisplayEnum(Value.POPUP, "popup");

    public static final DisplayEnum TOUCH = new DisplayEnum(Value.TOUCH, "touch");

    private final Value value;

    private final String string;

    DisplayEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof DisplayEnum && this.string.equals(((DisplayEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case WAP:
                return visitor.visitWap();
            case PAGE:
                return visitor.visitPage();
            case POPUP:
                return visitor.visitPopup();
            case TOUCH:
                return visitor.visitTouch();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DisplayEnum valueOf(String value) {
        switch (value) {
            case "wap":
                return WAP;
            case "page":
                return PAGE;
            case "popup":
                return POPUP;
            case "touch":
                return TOUCH;
            default:
                return new DisplayEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PAGE,

        POPUP,

        TOUCH,

        WAP,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitPage();

        T visitPopup();

        T visitTouch();

        T visitWap();

        T visitUnknown(String unknownType);
    }
}
