/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ErrorResponse.Builder.class)
public final class ErrorResponse {
    private final String type;

    private final double status;

    private final String title;

    private final String detail;

    private final Optional<List<ValidationError>> validationErrors;

    private final Map<String, Object> additionalProperties;

    private ErrorResponse(
            String type,
            double status,
            String title,
            String detail,
            Optional<List<ValidationError>> validationErrors,
            Map<String, Object> additionalProperties) {
        this.type = type;
        this.status = status;
        this.title = title;
        this.detail = detail;
        this.validationErrors = validationErrors;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("type")
    public String getType() {
        return type;
    }

    @JsonProperty("status")
    public double getStatus() {
        return status;
    }

    @JsonProperty("title")
    public String getTitle() {
        return title;
    }

    @JsonProperty("detail")
    public String getDetail() {
        return detail;
    }

    @JsonProperty("validation_errors")
    public Optional<List<ValidationError>> getValidationErrors() {
        return validationErrors;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ErrorResponse && equalTo((ErrorResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ErrorResponse other) {
        return type.equals(other.type)
                && status == other.status
                && title.equals(other.title)
                && detail.equals(other.detail)
                && validationErrors.equals(other.validationErrors);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.status, this.title, this.detail, this.validationErrors);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        StatusStage type(@NotNull String type);

        Builder from(ErrorResponse other);
    }

    public interface StatusStage {
        TitleStage status(double status);
    }

    public interface TitleStage {
        DetailStage title(@NotNull String title);
    }

    public interface DetailStage {
        _FinalStage detail(@NotNull String detail);
    }

    public interface _FinalStage {
        ErrorResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage validationErrors(Optional<List<ValidationError>> validationErrors);

        _FinalStage validationErrors(List<ValidationError> validationErrors);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, StatusStage, TitleStage, DetailStage, _FinalStage {
        private String type;

        private double status;

        private String title;

        private String detail;

        private Optional<List<ValidationError>> validationErrors = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ErrorResponse other) {
            type(other.getType());
            status(other.getStatus());
            title(other.getTitle());
            detail(other.getDetail());
            validationErrors(other.getValidationErrors());
            return this;
        }

        @java.lang.Override
        @JsonSetter("type")
        public StatusStage type(@NotNull String type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public TitleStage status(double status) {
            this.status = status;
            return this;
        }

        @java.lang.Override
        @JsonSetter("title")
        public DetailStage title(@NotNull String title) {
            this.title = Objects.requireNonNull(title, "title must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("detail")
        public _FinalStage detail(@NotNull String detail) {
            this.detail = Objects.requireNonNull(detail, "detail must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage validationErrors(List<ValidationError> validationErrors) {
            this.validationErrors = Optional.ofNullable(validationErrors);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "validation_errors", nulls = Nulls.SKIP)
        public _FinalStage validationErrors(Optional<List<ValidationError>> validationErrors) {
            this.validationErrors = validationErrors;
            return this;
        }

        @java.lang.Override
        public ErrorResponse build() {
            return new ErrorResponse(type, status, title, detail, validationErrors, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
