/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class FactorTypeEnum {
    public static final FactorTypeEnum WEBAUTHN_PLATFORM =
            new FactorTypeEnum(Value.WEBAUTHN_PLATFORM, "webauthn-platform");

    public static final FactorTypeEnum TOTP = new FactorTypeEnum(Value.TOTP, "totp");

    public static final FactorTypeEnum EMAIL = new FactorTypeEnum(Value.EMAIL, "email");

    public static final FactorTypeEnum PASSWORD = new FactorTypeEnum(Value.PASSWORD, "password");

    public static final FactorTypeEnum PASSKEY = new FactorTypeEnum(Value.PASSKEY, "passkey");

    public static final FactorTypeEnum WEBAUTHN_ROAMING =
            new FactorTypeEnum(Value.WEBAUTHN_ROAMING, "webauthn-roaming");

    public static final FactorTypeEnum PHONE = new FactorTypeEnum(Value.PHONE, "phone");

    public static final FactorTypeEnum RECOVERY_CODE = new FactorTypeEnum(Value.RECOVERY_CODE, "recovery-code");

    public static final FactorTypeEnum PUSH_NOTIFICATION =
            new FactorTypeEnum(Value.PUSH_NOTIFICATION, "push-notification");

    private final Value value;

    private final String string;

    FactorTypeEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof FactorTypeEnum && this.string.equals(((FactorTypeEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case WEBAUTHN_PLATFORM:
                return visitor.visitWebauthnPlatform();
            case TOTP:
                return visitor.visitTotp();
            case EMAIL:
                return visitor.visitEmail();
            case PASSWORD:
                return visitor.visitPassword();
            case PASSKEY:
                return visitor.visitPasskey();
            case WEBAUTHN_ROAMING:
                return visitor.visitWebauthnRoaming();
            case PHONE:
                return visitor.visitPhone();
            case RECOVERY_CODE:
                return visitor.visitRecoveryCode();
            case PUSH_NOTIFICATION:
                return visitor.visitPushNotification();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static FactorTypeEnum valueOf(String value) {
        switch (value) {
            case "webauthn-platform":
                return WEBAUTHN_PLATFORM;
            case "totp":
                return TOTP;
            case "email":
                return EMAIL;
            case "password":
                return PASSWORD;
            case "passkey":
                return PASSKEY;
            case "webauthn-roaming":
                return WEBAUTHN_ROAMING;
            case "phone":
                return PHONE;
            case "recovery-code":
                return RECOVERY_CODE;
            case "push-notification":
                return PUSH_NOTIFICATION;
            default:
                return new FactorTypeEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PASSWORD,

        PASSKEY,

        WEBAUTHN_PLATFORM,

        WEBAUTHN_ROAMING,

        TOTP,

        PHONE,

        EMAIL,

        PUSH_NOTIFICATION,

        RECOVERY_CODE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitPassword();

        T visitPasskey();

        T visitWebauthnPlatform();

        T visitWebauthnRoaming();

        T visitTotp();

        T visitPhone();

        T visitEmail();

        T visitPushNotification();

        T visitRecoveryCode();

        T visitUnknown(String unknownType);
    }
}
