/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import java.time.OffsetDateTime;
import java.util.List;

public interface IAuthenticationMethodBase {
    String getId();

    OffsetDateTime getCreatedAt();

    List<UsageEnum> getUsage();
}
