/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import java.util.Optional;

public interface IAuthenticationMethodWebAuthn extends IAuthenticationMethodMfaBase {
    Optional<String> getName();

    Optional<String> getKeyId();

    Optional<String> getPublicKey();
}
