/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import java.time.OffsetDateTime;
import java.util.Optional;

public interface IAuthenticationMethodMfaBase extends IAuthenticationMethodBase {
    boolean getConfirmed();

    Optional<OffsetDateTime> getLastAuthAt();
}
