/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IdentityAuthenticationMethodBase.Builder.class)
public final class IdentityAuthenticationMethodBase implements IIdentityAuthenticationMethodBase {
    private final Optional<String> connection;

    private final Optional<String> identityUserId;

    private final Map<String, Object> additionalProperties;

    private IdentityAuthenticationMethodBase(
            Optional<String> connection, Optional<String> identityUserId, Map<String, Object> additionalProperties) {
        this.connection = connection;
        this.identityUserId = identityUserId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("connection")
    @java.lang.Override
    public Optional<String> getConnection() {
        return connection;
    }

    @JsonProperty("identity_user_id")
    @java.lang.Override
    public Optional<String> getIdentityUserId() {
        return identityUserId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IdentityAuthenticationMethodBase && equalTo((IdentityAuthenticationMethodBase) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IdentityAuthenticationMethodBase other) {
        return connection.equals(other.connection) && identityUserId.equals(other.identityUserId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.connection, this.identityUserId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> connection = Optional.empty();

        private Optional<String> identityUserId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(IdentityAuthenticationMethodBase other) {
            connection(other.getConnection());
            identityUserId(other.getIdentityUserId());
            return this;
        }

        @JsonSetter(value = "connection", nulls = Nulls.SKIP)
        public Builder connection(Optional<String> connection) {
            this.connection = connection;
            return this;
        }

        public Builder connection(String connection) {
            this.connection = Optional.ofNullable(connection);
            return this;
        }

        @JsonSetter(value = "identity_user_id", nulls = Nulls.SKIP)
        public Builder identityUserId(Optional<String> identityUserId) {
            this.identityUserId = identityUserId;
            return this;
        }

        public Builder identityUserId(String identityUserId) {
            this.identityUserId = Optional.ofNullable(identityUserId);
            return this;
        }

        public IdentityAuthenticationMethodBase build() {
            return new IdentityAuthenticationMethodBase(connection, identityUserId, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
