/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

public interface IMfaBaseCreationResponse {
    String getId();

    String getAuthSession();
}
