/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListAuthenticationMethodsResponseContent.Builder.class)
public final class ListAuthenticationMethodsResponseContent {
    private final List<AuthenticationMethod> authenticationMethods;

    private final Map<String, Object> additionalProperties;

    private ListAuthenticationMethodsResponseContent(
            List<AuthenticationMethod> authenticationMethods, Map<String, Object> additionalProperties) {
        this.authenticationMethods = authenticationMethods;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("authentication_methods")
    public List<AuthenticationMethod> getAuthenticationMethods() {
        return authenticationMethods;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListAuthenticationMethodsResponseContent
                && equalTo((ListAuthenticationMethodsResponseContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListAuthenticationMethodsResponseContent other) {
        return authenticationMethods.equals(other.authenticationMethods);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.authenticationMethods);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<AuthenticationMethod> authenticationMethods = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListAuthenticationMethodsResponseContent other) {
            authenticationMethods(other.getAuthenticationMethods());
            return this;
        }

        @JsonSetter(value = "authentication_methods", nulls = Nulls.SKIP)
        public Builder authenticationMethods(List<AuthenticationMethod> authenticationMethods) {
            this.authenticationMethods.clear();
            if (authenticationMethods != null) {
                this.authenticationMethods.addAll(authenticationMethods);
            }
            return this;
        }

        public Builder addAuthenticationMethods(AuthenticationMethod authenticationMethods) {
            this.authenticationMethods.add(authenticationMethods);
            return this;
        }

        public Builder addAllAuthenticationMethods(List<AuthenticationMethod> authenticationMethods) {
            if (authenticationMethods != null) {
                this.authenticationMethods.addAll(authenticationMethods);
            }
            return this;
        }

        public ListAuthenticationMethodsResponseContent build() {
            return new ListAuthenticationMethodsResponseContent(authenticationMethods, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
