/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListFactorsResponseContent.Builder.class)
public final class ListFactorsResponseContent {
    private final List<Factor> factors;

    private final Map<String, Object> additionalProperties;

    private ListFactorsResponseContent(List<Factor> factors, Map<String, Object> additionalProperties) {
        this.factors = factors;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("factors")
    public List<Factor> getFactors() {
        return factors;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListFactorsResponseContent && equalTo((ListFactorsResponseContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListFactorsResponseContent other) {
        return factors.equals(other.factors);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.factors);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<Factor> factors = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListFactorsResponseContent other) {
            factors(other.getFactors());
            return this;
        }

        @JsonSetter(value = "factors", nulls = Nulls.SKIP)
        public Builder factors(List<Factor> factors) {
            this.factors.clear();
            if (factors != null) {
                this.factors.addAll(factors);
            }
            return this;
        }

        public Builder addFactors(Factor factors) {
            this.factors.add(factors);
            return this;
        }

        public Builder addAllFactors(List<Factor> factors) {
            if (factors != null) {
                this.factors.addAll(factors);
            }
            return this;
        }

        public ListFactorsResponseContent build() {
            return new ListFactorsResponseContent(factors, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
