/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListConnectedAccountsResponseContent.Builder.class)
public final class ListConnectedAccountsResponseContent {
    private final List<ConnectedAccount> accounts;

    private final Optional<String> next;

    private final Map<String, Object> additionalProperties;

    private ListConnectedAccountsResponseContent(
            List<ConnectedAccount> accounts, Optional<String> next, Map<String, Object> additionalProperties) {
        this.accounts = accounts;
        this.next = next;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("accounts")
    public List<ConnectedAccount> getAccounts() {
        return accounts;
    }

    /**
     * @return The token to retrieve the next page of connected accounts (if there is one)
     */
    @JsonProperty("next")
    public Optional<String> getNext() {
        return next;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListConnectedAccountsResponseContent
                && equalTo((ListConnectedAccountsResponseContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListConnectedAccountsResponseContent other) {
        return accounts.equals(other.accounts) && next.equals(other.next);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.accounts, this.next);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<ConnectedAccount> accounts = new ArrayList<>();

        private Optional<String> next = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListConnectedAccountsResponseContent other) {
            accounts(other.getAccounts());
            next(other.getNext());
            return this;
        }

        @JsonSetter(value = "accounts", nulls = Nulls.SKIP)
        public Builder accounts(List<ConnectedAccount> accounts) {
            this.accounts.clear();
            if (accounts != null) {
                this.accounts.addAll(accounts);
            }
            return this;
        }

        public Builder addAccounts(ConnectedAccount accounts) {
            this.accounts.add(accounts);
            return this;
        }

        public Builder addAllAccounts(List<ConnectedAccount> accounts) {
            if (accounts != null) {
                this.accounts.addAll(accounts);
            }
            return this;
        }

        /**
         * <p>The token to retrieve the next page of connected accounts (if there is one)</p>
         */
        @JsonSetter(value = "next", nulls = Nulls.SKIP)
        public Builder next(Optional<String> next) {
            this.next = next;
            return this;
        }

        public Builder next(String next) {
            this.next = Optional.ofNullable(next);
            return this;
        }

        public ListConnectedAccountsResponseContent build() {
            return new ListConnectedAccountsResponseContent(accounts, next, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
