/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.NullableNonemptyFilter;
import com.auth0.client.myaccount.core.ObjectMappers;
import com.auth0.client.myaccount.core.OptionalNullable;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.Nullable;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListAuthenticationMethodsRequestParameters.Builder.class)
public final class ListAuthenticationMethodsRequestParameters {
    private final OptionalNullable<FactorTypeEnum> type;

    private final Map<String, Object> additionalProperties;

    private ListAuthenticationMethodsRequestParameters(
            OptionalNullable<FactorTypeEnum> type, Map<String, Object> additionalProperties) {
        this.type = type;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Filter authentication methods by type
     */
    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("type")
    public OptionalNullable<FactorTypeEnum> getType() {
        if (type == null) {
            return OptionalNullable.absent();
        }
        return type;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("type")
    private OptionalNullable<FactorTypeEnum> _getType() {
        return type;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListAuthenticationMethodsRequestParameters
                && equalTo((ListAuthenticationMethodsRequestParameters) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListAuthenticationMethodsRequestParameters other) {
        return type.equals(other.type);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private OptionalNullable<FactorTypeEnum> type = OptionalNullable.absent();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListAuthenticationMethodsRequestParameters other) {
            type(other.getType());
            return this;
        }

        /**
         * <p>Filter authentication methods by type</p>
         */
        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(@Nullable OptionalNullable<FactorTypeEnum> type) {
            this.type = type;
            return this;
        }

        public Builder type(FactorTypeEnum type) {
            this.type = OptionalNullable.of(type);
            return this;
        }

        public Builder type(Optional<FactorTypeEnum> type) {
            if (type.isPresent()) {
                this.type = OptionalNullable.of(type.get());
            } else {
                this.type = OptionalNullable.absent();
            }
            return this;
        }

        public Builder type(com.auth0.client.myaccount.core.Nullable<FactorTypeEnum> type) {
            if (type.isNull()) {
                this.type = OptionalNullable.ofNull();
            } else if (type.isEmpty()) {
                this.type = OptionalNullable.absent();
            } else {
                this.type = OptionalNullable.of(type.get());
            }
            return this;
        }

        public ListAuthenticationMethodsRequestParameters build() {
            return new ListAuthenticationMethodsRequestParameters(type, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
