/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MfaBaseCreationResponse.Builder.class)
public final class MfaBaseCreationResponse implements IMfaBaseCreationResponse {
    private final String id;

    private final String authSession;

    private final Map<String, Object> additionalProperties;

    private MfaBaseCreationResponse(String id, String authSession, Map<String, Object> additionalProperties) {
        this.id = id;
        this.authSession = authSession;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique identifier for the authentication method.
     */
    @JsonProperty("id")
    @java.lang.Override
    public String getId() {
        return id;
    }

    /**
     * @return The unique session identifier for the enrollment.
     */
    @JsonProperty("auth_session")
    @java.lang.Override
    public String getAuthSession() {
        return authSession;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MfaBaseCreationResponse && equalTo((MfaBaseCreationResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MfaBaseCreationResponse other) {
        return id.equals(other.id) && authSession.equals(other.authSession);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.authSession);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>The unique identifier for the authentication method.</p>
         */
        AuthSessionStage id(@NotNull String id);

        Builder from(MfaBaseCreationResponse other);
    }

    public interface AuthSessionStage {
        /**
         * <p>The unique session identifier for the enrollment.</p>
         */
        _FinalStage authSession(@NotNull String authSession);
    }

    public interface _FinalStage {
        MfaBaseCreationResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, AuthSessionStage, _FinalStage {
        private String id;

        private String authSession;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(MfaBaseCreationResponse other) {
            id(other.getId());
            authSession(other.getAuthSession());
            return this;
        }

        /**
         * <p>The unique identifier for the authentication method.</p>
         * <p>The unique identifier for the authentication method.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public AuthSessionStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The unique session identifier for the enrollment.</p>
         * <p>The unique session identifier for the enrollment.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("auth_session")
        public _FinalStage authSession(@NotNull String authSession) {
            this.authSession = Objects.requireNonNull(authSession, "authSession must not be null");
            return this;
        }

        @java.lang.Override
        public MfaBaseCreationResponse build() {
            return new MfaBaseCreationResponse(id, authSession, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
