/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PasswordDictionaryPolicy.Builder.class)
public final class PasswordDictionaryPolicy {
    private final boolean active;

    private final PasswordDictionaryDefaultEnum default_;

    private final Map<String, Object> additionalProperties;

    private PasswordDictionaryPolicy(
            boolean active, PasswordDictionaryDefaultEnum default_, Map<String, Object> additionalProperties) {
        this.active = active;
        this.default_ = default_;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Whether dictionary checking is enabled
     */
    @JsonProperty("active")
    public boolean getActive() {
        return active;
    }

    @JsonProperty("default")
    public PasswordDictionaryDefaultEnum getDefault() {
        return default_;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PasswordDictionaryPolicy && equalTo((PasswordDictionaryPolicy) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PasswordDictionaryPolicy other) {
        return active == other.active && default_.equals(other.default_);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.active, this.default_);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ActiveStage builder() {
        return new Builder();
    }

    public interface ActiveStage {
        /**
         * <p>Whether dictionary checking is enabled</p>
         */
        DefaultStage active(boolean active);

        Builder from(PasswordDictionaryPolicy other);
    }

    public interface DefaultStage {
        _FinalStage default_(@NotNull PasswordDictionaryDefaultEnum default_);
    }

    public interface _FinalStage {
        PasswordDictionaryPolicy build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ActiveStage, DefaultStage, _FinalStage {
        private boolean active;

        private PasswordDictionaryDefaultEnum default_;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PasswordDictionaryPolicy other) {
            active(other.getActive());
            default_(other.getDefault());
            return this;
        }

        /**
         * <p>Whether dictionary checking is enabled</p>
         * <p>Whether dictionary checking is enabled</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("active")
        public DefaultStage active(boolean active) {
            this.active = active;
            return this;
        }

        @java.lang.Override
        @JsonSetter("default")
        public _FinalStage default_(@NotNull PasswordDictionaryDefaultEnum default_) {
            this.default_ = Objects.requireNonNull(default_, "default_ must not be null");
            return this;
        }

        @java.lang.Override
        public PasswordDictionaryPolicy build() {
            return new PasswordDictionaryPolicy(active, default_, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
