/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PasswordProfileDataPolicy.Builder.class)
public final class PasswordProfileDataPolicy {
    private final boolean active;

    private final List<String> blockedFields;

    private final Map<String, Object> additionalProperties;

    private PasswordProfileDataPolicy(
            boolean active, List<String> blockedFields, Map<String, Object> additionalProperties) {
        this.active = active;
        this.blockedFields = blockedFields;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Whether to block personal information (name, email, etc.) in passwords
     */
    @JsonProperty("active")
    public boolean getActive() {
        return active;
    }

    /**
     * @return User profile fields to block from passwords (e.g., 'name', 'email', 'user_metadata.first')
     */
    @JsonProperty("blocked_fields")
    public List<String> getBlockedFields() {
        return blockedFields;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PasswordProfileDataPolicy && equalTo((PasswordProfileDataPolicy) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PasswordProfileDataPolicy other) {
        return active == other.active && blockedFields.equals(other.blockedFields);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.active, this.blockedFields);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ActiveStage builder() {
        return new Builder();
    }

    public interface ActiveStage {
        /**
         * <p>Whether to block personal information (name, email, etc.) in passwords</p>
         */
        _FinalStage active(boolean active);

        Builder from(PasswordProfileDataPolicy other);
    }

    public interface _FinalStage {
        PasswordProfileDataPolicy build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>User profile fields to block from passwords (e.g., 'name', 'email', 'user_metadata.first')</p>
         */
        _FinalStage blockedFields(List<String> blockedFields);

        _FinalStage addBlockedFields(String blockedFields);

        _FinalStage addAllBlockedFields(List<String> blockedFields);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ActiveStage, _FinalStage {
        private boolean active;

        private List<String> blockedFields = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PasswordProfileDataPolicy other) {
            active(other.getActive());
            blockedFields(other.getBlockedFields());
            return this;
        }

        /**
         * <p>Whether to block personal information (name, email, etc.) in passwords</p>
         * <p>Whether to block personal information (name, email, etc.) in passwords</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("active")
        public _FinalStage active(boolean active) {
            this.active = active;
            return this;
        }

        /**
         * <p>User profile fields to block from passwords (e.g., 'name', 'email', 'user_metadata.first')</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllBlockedFields(List<String> blockedFields) {
            if (blockedFields != null) {
                this.blockedFields.addAll(blockedFields);
            }
            return this;
        }

        /**
         * <p>User profile fields to block from passwords (e.g., 'name', 'email', 'user_metadata.first')</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addBlockedFields(String blockedFields) {
            this.blockedFields.add(blockedFields);
            return this;
        }

        /**
         * <p>User profile fields to block from passwords (e.g., 'name', 'email', 'user_metadata.first')</p>
         */
        @java.lang.Override
        @JsonSetter(value = "blocked_fields", nulls = Nulls.SKIP)
        public _FinalStage blockedFields(List<String> blockedFields) {
            this.blockedFields.clear();
            if (blockedFields != null) {
                this.blockedFields.addAll(blockedFields);
            }
            return this;
        }

        @java.lang.Override
        public PasswordProfileDataPolicy build() {
            return new PasswordProfileDataPolicy(active, blockedFields, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
