/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PasswordAuthenticationMethodPolicy.Builder.class)
public final class PasswordAuthenticationMethodPolicy {
    private final PasswordComplexityPolicy complexity;

    private final PasswordProfileDataPolicy profileData;

    private final PasswordHistoryPolicy history;

    private final PasswordDictionaryPolicy dictionary;

    private final Map<String, Object> additionalProperties;

    private PasswordAuthenticationMethodPolicy(
            PasswordComplexityPolicy complexity,
            PasswordProfileDataPolicy profileData,
            PasswordHistoryPolicy history,
            PasswordDictionaryPolicy dictionary,
            Map<String, Object> additionalProperties) {
        this.complexity = complexity;
        this.profileData = profileData;
        this.history = history;
        this.dictionary = dictionary;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("complexity")
    public PasswordComplexityPolicy getComplexity() {
        return complexity;
    }

    @JsonProperty("profile_data")
    public PasswordProfileDataPolicy getProfileData() {
        return profileData;
    }

    @JsonProperty("history")
    public PasswordHistoryPolicy getHistory() {
        return history;
    }

    @JsonProperty("dictionary")
    public PasswordDictionaryPolicy getDictionary() {
        return dictionary;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PasswordAuthenticationMethodPolicy
                && equalTo((PasswordAuthenticationMethodPolicy) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PasswordAuthenticationMethodPolicy other) {
        return complexity.equals(other.complexity)
                && profileData.equals(other.profileData)
                && history.equals(other.history)
                && dictionary.equals(other.dictionary);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.complexity, this.profileData, this.history, this.dictionary);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ComplexityStage builder() {
        return new Builder();
    }

    public interface ComplexityStage {
        ProfileDataStage complexity(@NotNull PasswordComplexityPolicy complexity);

        Builder from(PasswordAuthenticationMethodPolicy other);
    }

    public interface ProfileDataStage {
        HistoryStage profileData(@NotNull PasswordProfileDataPolicy profileData);
    }

    public interface HistoryStage {
        DictionaryStage history(@NotNull PasswordHistoryPolicy history);
    }

    public interface DictionaryStage {
        _FinalStage dictionary(@NotNull PasswordDictionaryPolicy dictionary);
    }

    public interface _FinalStage {
        PasswordAuthenticationMethodPolicy build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ComplexityStage, ProfileDataStage, HistoryStage, DictionaryStage, _FinalStage {
        private PasswordComplexityPolicy complexity;

        private PasswordProfileDataPolicy profileData;

        private PasswordHistoryPolicy history;

        private PasswordDictionaryPolicy dictionary;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PasswordAuthenticationMethodPolicy other) {
            complexity(other.getComplexity());
            profileData(other.getProfileData());
            history(other.getHistory());
            dictionary(other.getDictionary());
            return this;
        }

        @java.lang.Override
        @JsonSetter("complexity")
        public ProfileDataStage complexity(@NotNull PasswordComplexityPolicy complexity) {
            this.complexity = Objects.requireNonNull(complexity, "complexity must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("profile_data")
        public HistoryStage profileData(@NotNull PasswordProfileDataPolicy profileData) {
            this.profileData = Objects.requireNonNull(profileData, "profileData must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("history")
        public DictionaryStage history(@NotNull PasswordHistoryPolicy history) {
            this.history = Objects.requireNonNull(history, "history must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("dictionary")
        public _FinalStage dictionary(@NotNull PasswordDictionaryPolicy dictionary) {
            this.dictionary = Objects.requireNonNull(dictionary, "dictionary must not be null");
            return this;
        }

        @java.lang.Override
        public PasswordAuthenticationMethodPolicy build() {
            return new PasswordAuthenticationMethodPolicy(
                    complexity, profileData, history, dictionary, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
