/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PasswordCreationResponse.Builder.class)
public final class PasswordCreationResponse {
    private final String id;

    private final PasswordAuthenticationMethodPolicy policy;

    private final String authSession;

    private final Map<String, Object> additionalProperties;

    private PasswordCreationResponse(
            String id,
            PasswordAuthenticationMethodPolicy policy,
            String authSession,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.policy = policy;
        this.authSession = authSession;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique identifier for the password authentication method.
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("policy")
    public PasswordAuthenticationMethodPolicy getPolicy() {
        return policy;
    }

    /**
     * @return The unique session identifier for the password change operation.
     */
    @JsonProperty("auth_session")
    public String getAuthSession() {
        return authSession;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PasswordCreationResponse && equalTo((PasswordCreationResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PasswordCreationResponse other) {
        return id.equals(other.id) && policy.equals(other.policy) && authSession.equals(other.authSession);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.policy, this.authSession);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>The unique identifier for the password authentication method.</p>
         */
        PolicyStage id(@NotNull String id);

        Builder from(PasswordCreationResponse other);
    }

    public interface PolicyStage {
        AuthSessionStage policy(@NotNull PasswordAuthenticationMethodPolicy policy);
    }

    public interface AuthSessionStage {
        /**
         * <p>The unique session identifier for the password change operation.</p>
         */
        _FinalStage authSession(@NotNull String authSession);
    }

    public interface _FinalStage {
        PasswordCreationResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, PolicyStage, AuthSessionStage, _FinalStage {
        private String id;

        private PasswordAuthenticationMethodPolicy policy;

        private String authSession;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PasswordCreationResponse other) {
            id(other.getId());
            policy(other.getPolicy());
            authSession(other.getAuthSession());
            return this;
        }

        /**
         * <p>The unique identifier for the password authentication method.</p>
         * <p>The unique identifier for the password authentication method.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public PolicyStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("policy")
        public AuthSessionStage policy(@NotNull PasswordAuthenticationMethodPolicy policy) {
            this.policy = Objects.requireNonNull(policy, "policy must not be null");
            return this;
        }

        /**
         * <p>The unique session identifier for the password change operation.</p>
         * <p>The unique session identifier for the password change operation.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("auth_session")
        public _FinalStage authSession(@NotNull String authSession) {
            this.authSession = Objects.requireNonNull(authSession, "authSession must not be null");
            return this;
        }

        @java.lang.Override
        public PasswordCreationResponse build() {
            return new PasswordCreationResponse(id, policy, authSession, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
