/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PasswordHistoryPolicy.Builder.class)
public final class PasswordHistoryPolicy {
    private final boolean active;

    private final int size;

    private final Map<String, Object> additionalProperties;

    private PasswordHistoryPolicy(boolean active, int size, Map<String, Object> additionalProperties) {
        this.active = active;
        this.size = size;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Whether password history is enforced
     */
    @JsonProperty("active")
    public boolean getActive() {
        return active;
    }

    /**
     * @return Number of previous passwords to remember and prevent reuse
     */
    @JsonProperty("size")
    public int getSize() {
        return size;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PasswordHistoryPolicy && equalTo((PasswordHistoryPolicy) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PasswordHistoryPolicy other) {
        return active == other.active && size == other.size;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.active, this.size);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ActiveStage builder() {
        return new Builder();
    }

    public interface ActiveStage {
        /**
         * <p>Whether password history is enforced</p>
         */
        SizeStage active(boolean active);

        Builder from(PasswordHistoryPolicy other);
    }

    public interface SizeStage {
        /**
         * <p>Number of previous passwords to remember and prevent reuse</p>
         */
        _FinalStage size(int size);
    }

    public interface _FinalStage {
        PasswordHistoryPolicy build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ActiveStage, SizeStage, _FinalStage {
        private boolean active;

        private int size;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PasswordHistoryPolicy other) {
            active(other.getActive());
            size(other.getSize());
            return this;
        }

        /**
         * <p>Whether password history is enforced</p>
         * <p>Whether password history is enforced</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("active")
        public SizeStage active(boolean active) {
            this.active = active;
            return this;
        }

        /**
         * <p>Number of previous passwords to remember and prevent reuse</p>
         * <p>Number of previous passwords to remember and prevent reuse</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("size")
        public _FinalStage size(int size) {
            this.size = size;
            return this;
        }

        @java.lang.Override
        public PasswordHistoryPolicy build() {
            return new PasswordHistoryPolicy(active, size, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
