/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PasswordSequentialCharactersEnum {
    public static final PasswordSequentialCharactersEnum ALLOW =
            new PasswordSequentialCharactersEnum(Value.ALLOW, "allow");

    public static final PasswordSequentialCharactersEnum BLOCK =
            new PasswordSequentialCharactersEnum(Value.BLOCK, "block");

    private final Value value;

    private final String string;

    PasswordSequentialCharactersEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PasswordSequentialCharactersEnum
                        && this.string.equals(((PasswordSequentialCharactersEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ALLOW:
                return visitor.visitAllow();
            case BLOCK:
                return visitor.visitBlock();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PasswordSequentialCharactersEnum valueOf(String value) {
        switch (value) {
            case "allow":
                return ALLOW;
            case "block":
                return BLOCK;
            default:
                return new PasswordSequentialCharactersEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ALLOW,

        BLOCK,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAllow();

        T visitBlock();

        T visitUnknown(String unknownType);
    }
}
