/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PasswordCharacterTypeRuleEnum {
    public static final PasswordCharacterTypeRuleEnum ALL = new PasswordCharacterTypeRuleEnum(Value.ALL, "all");

    public static final PasswordCharacterTypeRuleEnum THREE_OF_FOUR =
            new PasswordCharacterTypeRuleEnum(Value.THREE_OF_FOUR, "three_of_four");

    private final Value value;

    private final String string;

    PasswordCharacterTypeRuleEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PasswordCharacterTypeRuleEnum
                        && this.string.equals(((PasswordCharacterTypeRuleEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ALL:
                return visitor.visitAll();
            case THREE_OF_FOUR:
                return visitor.visitThreeOfFour();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PasswordCharacterTypeRuleEnum valueOf(String value) {
        switch (value) {
            case "all":
                return ALL;
            case "three_of_four":
                return THREE_OF_FOUR;
            default:
                return new PasswordCharacterTypeRuleEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ALL,

        THREE_OF_FOUR,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAll();

        T visitThreeOfFour();

        T visitUnknown(String unknownType);
    }
}
