/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PasswordMaxLengthExceededEnum {
    public static final PasswordMaxLengthExceededEnum TRUNCATE =
            new PasswordMaxLengthExceededEnum(Value.TRUNCATE, "truncate");

    public static final PasswordMaxLengthExceededEnum ERROR = new PasswordMaxLengthExceededEnum(Value.ERROR, "error");

    private final Value value;

    private final String string;

    PasswordMaxLengthExceededEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PasswordMaxLengthExceededEnum
                        && this.string.equals(((PasswordMaxLengthExceededEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case TRUNCATE:
                return visitor.visitTruncate();
            case ERROR:
                return visitor.visitError();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PasswordMaxLengthExceededEnum valueOf(String value) {
        switch (value) {
            case "truncate":
                return TRUNCATE;
            case "error":
                return ERROR;
            default:
                return new PasswordMaxLengthExceededEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        TRUNCATE,

        ERROR,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitTruncate();

        T visitError();

        T visitUnknown(String unknownType);
    }
}
