/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PhoneAuthenticationMethodEnum {
    public static final PhoneAuthenticationMethodEnum VOICE = new PhoneAuthenticationMethodEnum(Value.VOICE, "voice");

    public static final PhoneAuthenticationMethodEnum SMS = new PhoneAuthenticationMethodEnum(Value.SMS, "sms");

    private final Value value;

    private final String string;

    PhoneAuthenticationMethodEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PhoneAuthenticationMethodEnum
                        && this.string.equals(((PhoneAuthenticationMethodEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case VOICE:
                return visitor.visitVoice();
            case SMS:
                return visitor.visitSms();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PhoneAuthenticationMethodEnum valueOf(String value) {
        switch (value) {
            case "voice":
                return VOICE;
            case "sms":
                return SMS;
            default:
                return new PhoneAuthenticationMethodEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SMS,

        VOICE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSms();

        T visitVoice();

        T visitUnknown(String unknownType);
    }
}
