/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PublicKeyTypeEnum {
    public static final PublicKeyTypeEnum PUBLIC_KEY = new PublicKeyTypeEnum(Value.PUBLIC_KEY, "public-key");

    private final Value value;

    private final String string;

    PublicKeyTypeEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PublicKeyTypeEnum && this.string.equals(((PublicKeyTypeEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PUBLIC_KEY:
                return visitor.visitPublicKey();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PublicKeyTypeEnum valueOf(String value) {
        switch (value) {
            case "public-key":
                return PUBLIC_KEY;
            default:
                return new PublicKeyTypeEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PUBLIC_KEY,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitPublicKey();

        T visitUnknown(String unknownType);
    }
}
