/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PublicKeyCredentialCreationOptions.Builder.class)
public final class PublicKeyCredentialCreationOptions {
    private final Optional<AuthenticatorSelection> authenticatorSelection;

    private final String challenge;

    private final List<PublicKeyCredentialParameter> pubKeyCredParams;

    private final RelyingParty rp;

    private final Optional<Double> timeout;

    private final User user;

    private final Map<String, Object> additionalProperties;

    private PublicKeyCredentialCreationOptions(
            Optional<AuthenticatorSelection> authenticatorSelection,
            String challenge,
            List<PublicKeyCredentialParameter> pubKeyCredParams,
            RelyingParty rp,
            Optional<Double> timeout,
            User user,
            Map<String, Object> additionalProperties) {
        this.authenticatorSelection = authenticatorSelection;
        this.challenge = challenge;
        this.pubKeyCredParams = pubKeyCredParams;
        this.rp = rp;
        this.timeout = timeout;
        this.user = user;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("authenticatorSelection")
    public Optional<AuthenticatorSelection> getAuthenticatorSelection() {
        return authenticatorSelection;
    }

    @JsonProperty("challenge")
    public String getChallenge() {
        return challenge;
    }

    @JsonProperty("pubKeyCredParams")
    public List<PublicKeyCredentialParameter> getPubKeyCredParams() {
        return pubKeyCredParams;
    }

    @JsonProperty("rp")
    public RelyingParty getRp() {
        return rp;
    }

    @JsonProperty("timeout")
    public Optional<Double> getTimeout() {
        return timeout;
    }

    @JsonProperty("user")
    public User getUser() {
        return user;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PublicKeyCredentialCreationOptions
                && equalTo((PublicKeyCredentialCreationOptions) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PublicKeyCredentialCreationOptions other) {
        return authenticatorSelection.equals(other.authenticatorSelection)
                && challenge.equals(other.challenge)
                && pubKeyCredParams.equals(other.pubKeyCredParams)
                && rp.equals(other.rp)
                && timeout.equals(other.timeout)
                && user.equals(other.user);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.authenticatorSelection, this.challenge, this.pubKeyCredParams, this.rp, this.timeout, this.user);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ChallengeStage builder() {
        return new Builder();
    }

    public interface ChallengeStage {
        RpStage challenge(@NotNull String challenge);

        Builder from(PublicKeyCredentialCreationOptions other);
    }

    public interface RpStage {
        UserStage rp(@NotNull RelyingParty rp);
    }

    public interface UserStage {
        _FinalStage user(@NotNull User user);
    }

    public interface _FinalStage {
        PublicKeyCredentialCreationOptions build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage authenticatorSelection(Optional<AuthenticatorSelection> authenticatorSelection);

        _FinalStage authenticatorSelection(AuthenticatorSelection authenticatorSelection);

        _FinalStage pubKeyCredParams(List<PublicKeyCredentialParameter> pubKeyCredParams);

        _FinalStage addPubKeyCredParams(PublicKeyCredentialParameter pubKeyCredParams);

        _FinalStage addAllPubKeyCredParams(List<PublicKeyCredentialParameter> pubKeyCredParams);

        _FinalStage timeout(Optional<Double> timeout);

        _FinalStage timeout(Double timeout);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ChallengeStage, RpStage, UserStage, _FinalStage {
        private String challenge;

        private RelyingParty rp;

        private User user;

        private Optional<Double> timeout = Optional.empty();

        private List<PublicKeyCredentialParameter> pubKeyCredParams = new ArrayList<>();

        private Optional<AuthenticatorSelection> authenticatorSelection = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PublicKeyCredentialCreationOptions other) {
            authenticatorSelection(other.getAuthenticatorSelection());
            challenge(other.getChallenge());
            pubKeyCredParams(other.getPubKeyCredParams());
            rp(other.getRp());
            timeout(other.getTimeout());
            user(other.getUser());
            return this;
        }

        @java.lang.Override
        @JsonSetter("challenge")
        public RpStage challenge(@NotNull String challenge) {
            this.challenge = Objects.requireNonNull(challenge, "challenge must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("rp")
        public UserStage rp(@NotNull RelyingParty rp) {
            this.rp = Objects.requireNonNull(rp, "rp must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("user")
        public _FinalStage user(@NotNull User user) {
            this.user = Objects.requireNonNull(user, "user must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage timeout(Double timeout) {
            this.timeout = Optional.ofNullable(timeout);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "timeout", nulls = Nulls.SKIP)
        public _FinalStage timeout(Optional<Double> timeout) {
            this.timeout = timeout;
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllPubKeyCredParams(List<PublicKeyCredentialParameter> pubKeyCredParams) {
            if (pubKeyCredParams != null) {
                this.pubKeyCredParams.addAll(pubKeyCredParams);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addPubKeyCredParams(PublicKeyCredentialParameter pubKeyCredParams) {
            this.pubKeyCredParams.add(pubKeyCredParams);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "pubKeyCredParams", nulls = Nulls.SKIP)
        public _FinalStage pubKeyCredParams(List<PublicKeyCredentialParameter> pubKeyCredParams) {
            this.pubKeyCredParams.clear();
            if (pubKeyCredParams != null) {
                this.pubKeyCredParams.addAll(pubKeyCredParams);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage authenticatorSelection(AuthenticatorSelection authenticatorSelection) {
            this.authenticatorSelection = Optional.ofNullable(authenticatorSelection);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "authenticatorSelection", nulls = Nulls.SKIP)
        public _FinalStage authenticatorSelection(Optional<AuthenticatorSelection> authenticatorSelection) {
            this.authenticatorSelection = authenticatorSelection;
            return this;
        }

        @java.lang.Override
        public PublicKeyCredentialCreationOptions build() {
            return new PublicKeyCredentialCreationOptions(
                    authenticatorSelection, challenge, pubKeyCredParams, rp, timeout, user, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
