/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = RecoveryCodeCreationResponse.Builder.class)
public final class RecoveryCodeCreationResponse implements IMfaBaseCreationResponse {
    private final String id;

    private final String authSession;

    private final String recoveryCode;

    private final Map<String, Object> additionalProperties;

    private RecoveryCodeCreationResponse(
            String id, String authSession, String recoveryCode, Map<String, Object> additionalProperties) {
        this.id = id;
        this.authSession = authSession;
        this.recoveryCode = recoveryCode;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique identifier for the authentication method.
     */
    @JsonProperty("id")
    @java.lang.Override
    public String getId() {
        return id;
    }

    /**
     * @return The unique session identifier for the enrollment.
     */
    @JsonProperty("auth_session")
    @java.lang.Override
    public String getAuthSession() {
        return authSession;
    }

    /**
     * @return The recovery code value.
     */
    @JsonProperty("recovery_code")
    public String getRecoveryCode() {
        return recoveryCode;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof RecoveryCodeCreationResponse && equalTo((RecoveryCodeCreationResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(RecoveryCodeCreationResponse other) {
        return id.equals(other.id) && authSession.equals(other.authSession) && recoveryCode.equals(other.recoveryCode);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.authSession, this.recoveryCode);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>The unique identifier for the authentication method.</p>
         */
        AuthSessionStage id(@NotNull String id);

        Builder from(RecoveryCodeCreationResponse other);
    }

    public interface AuthSessionStage {
        /**
         * <p>The unique session identifier for the enrollment.</p>
         */
        RecoveryCodeStage authSession(@NotNull String authSession);
    }

    public interface RecoveryCodeStage {
        /**
         * <p>The recovery code value.</p>
         */
        _FinalStage recoveryCode(@NotNull String recoveryCode);
    }

    public interface _FinalStage {
        RecoveryCodeCreationResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, AuthSessionStage, RecoveryCodeStage, _FinalStage {
        private String id;

        private String authSession;

        private String recoveryCode;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(RecoveryCodeCreationResponse other) {
            id(other.getId());
            authSession(other.getAuthSession());
            recoveryCode(other.getRecoveryCode());
            return this;
        }

        /**
         * <p>The unique identifier for the authentication method.</p>
         * <p>The unique identifier for the authentication method.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public AuthSessionStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The unique session identifier for the enrollment.</p>
         * <p>The unique session identifier for the enrollment.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("auth_session")
        public RecoveryCodeStage authSession(@NotNull String authSession) {
            this.authSession = Objects.requireNonNull(authSession, "authSession must not be null");
            return this;
        }

        /**
         * <p>The recovery code value.</p>
         * <p>The recovery code value.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("recovery_code")
        public _FinalStage recoveryCode(@NotNull String recoveryCode) {
            this.recoveryCode = Objects.requireNonNull(recoveryCode, "recoveryCode must not be null");
            return this;
        }

        @java.lang.Override
        public RecoveryCodeCreationResponse build() {
            return new RecoveryCodeCreationResponse(id, authSession, recoveryCode, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
