/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ResidentKeyEnum {
    public static final ResidentKeyEnum REQUIRED = new ResidentKeyEnum(Value.REQUIRED, "required");

    private final Value value;

    private final String string;

    ResidentKeyEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ResidentKeyEnum && this.string.equals(((ResidentKeyEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case REQUIRED:
                return visitor.visitRequired();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ResidentKeyEnum valueOf(String value) {
        switch (value) {
            case "required":
                return REQUIRED;
            default:
                return new ResidentKeyEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        REQUIRED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitRequired();

        T visitUnknown(String unknownType);
    }
}
