/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class UserVerificationEnum {
    public static final UserVerificationEnum REQUIRED = new UserVerificationEnum(Value.REQUIRED, "required");

    public static final UserVerificationEnum PREFERRED = new UserVerificationEnum(Value.PREFERRED, "preferred");

    public static final UserVerificationEnum DISCOURAGED = new UserVerificationEnum(Value.DISCOURAGED, "discouraged");

    private final Value value;

    private final String string;

    UserVerificationEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof UserVerificationEnum && this.string.equals(((UserVerificationEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case REQUIRED:
                return visitor.visitRequired();
            case PREFERRED:
                return visitor.visitPreferred();
            case DISCOURAGED:
                return visitor.visitDiscouraged();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static UserVerificationEnum valueOf(String value) {
        switch (value) {
            case "required":
                return REQUIRED;
            case "preferred":
                return PREFERRED;
            case "discouraged":
                return DISCOURAGED;
            default:
                return new UserVerificationEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        REQUIRED,

        PREFERRED,

        DISCOURAGED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitRequired();

        T visitPreferred();

        T visitDiscouraged();

        T visitUnknown(String unknownType);
    }
}
