/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ValidationError.Builder.class)
public final class ValidationError {
    private final String detail;

    private final Optional<String> field;

    private final Optional<String> pointer;

    private final Optional<String> source;

    private final Map<String, Object> additionalProperties;

    private ValidationError(
            String detail,
            Optional<String> field,
            Optional<String> pointer,
            Optional<String> source,
            Map<String, Object> additionalProperties) {
        this.detail = detail;
        this.field = field;
        this.pointer = pointer;
        this.source = source;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("detail")
    public String getDetail() {
        return detail;
    }

    @JsonProperty("field")
    public Optional<String> getField() {
        return field;
    }

    @JsonProperty("pointer")
    public Optional<String> getPointer() {
        return pointer;
    }

    @JsonProperty("source")
    public Optional<String> getSource() {
        return source;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ValidationError && equalTo((ValidationError) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ValidationError other) {
        return detail.equals(other.detail)
                && field.equals(other.field)
                && pointer.equals(other.pointer)
                && source.equals(other.source);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.detail, this.field, this.pointer, this.source);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DetailStage builder() {
        return new Builder();
    }

    public interface DetailStage {
        _FinalStage detail(@NotNull String detail);

        Builder from(ValidationError other);
    }

    public interface _FinalStage {
        ValidationError build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage field(Optional<String> field);

        _FinalStage field(String field);

        _FinalStage pointer(Optional<String> pointer);

        _FinalStage pointer(String pointer);

        _FinalStage source(Optional<String> source);

        _FinalStage source(String source);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements DetailStage, _FinalStage {
        private String detail;

        private Optional<String> source = Optional.empty();

        private Optional<String> pointer = Optional.empty();

        private Optional<String> field = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ValidationError other) {
            detail(other.getDetail());
            field(other.getField());
            pointer(other.getPointer());
            source(other.getSource());
            return this;
        }

        @java.lang.Override
        @JsonSetter("detail")
        public _FinalStage detail(@NotNull String detail) {
            this.detail = Objects.requireNonNull(detail, "detail must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage source(String source) {
            this.source = Optional.ofNullable(source);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "source", nulls = Nulls.SKIP)
        public _FinalStage source(Optional<String> source) {
            this.source = source;
            return this;
        }

        @java.lang.Override
        public _FinalStage pointer(String pointer) {
            this.pointer = Optional.ofNullable(pointer);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "pointer", nulls = Nulls.SKIP)
        public _FinalStage pointer(Optional<String> pointer) {
            this.pointer = pointer;
            return this;
        }

        @java.lang.Override
        public _FinalStage field(String field) {
            this.field = Optional.ofNullable(field);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "field", nulls = Nulls.SKIP)
        public _FinalStage field(Optional<String> field) {
            this.field = field;
            return this;
        }

        @java.lang.Override
        public ValidationError build() {
            return new ValidationError(detail, field, pointer, source, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
