/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = VerifyTotpAuthenticationMethod.Builder.class)
public final class VerifyTotpAuthenticationMethod {
    private final String authSession;

    private final String otpCode;

    private final Map<String, Object> additionalProperties;

    private VerifyTotpAuthenticationMethod(
            String authSession, String otpCode, Map<String, Object> additionalProperties) {
        this.authSession = authSession;
        this.otpCode = otpCode;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique session identifier for the enrollment as returned by POST /authentication-methods
     */
    @JsonProperty("auth_session")
    public String getAuthSession() {
        return authSession;
    }

    /**
     * @return The one-time password code retrieved from the TOTP application.
     */
    @JsonProperty("otp_code")
    public String getOtpCode() {
        return otpCode;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof VerifyTotpAuthenticationMethod && equalTo((VerifyTotpAuthenticationMethod) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(VerifyTotpAuthenticationMethod other) {
        return authSession.equals(other.authSession) && otpCode.equals(other.otpCode);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.authSession, this.otpCode);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AuthSessionStage builder() {
        return new Builder();
    }

    public interface AuthSessionStage {
        /**
         * <p>The unique session identifier for the enrollment as returned by POST /authentication-methods</p>
         */
        OtpCodeStage authSession(@NotNull String authSession);

        Builder from(VerifyTotpAuthenticationMethod other);
    }

    public interface OtpCodeStage {
        /**
         * <p>The one-time password code retrieved from the TOTP application.</p>
         */
        _FinalStage otpCode(@NotNull String otpCode);
    }

    public interface _FinalStage {
        VerifyTotpAuthenticationMethod build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AuthSessionStage, OtpCodeStage, _FinalStage {
        private String authSession;

        private String otpCode;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(VerifyTotpAuthenticationMethod other) {
            authSession(other.getAuthSession());
            otpCode(other.getOtpCode());
            return this;
        }

        /**
         * <p>The unique session identifier for the enrollment as returned by POST /authentication-methods</p>
         * <p>The unique session identifier for the enrollment as returned by POST /authentication-methods</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("auth_session")
        public OtpCodeStage authSession(@NotNull String authSession) {
            this.authSession = Objects.requireNonNull(authSession, "authSession must not be null");
            return this;
        }

        /**
         * <p>The one-time password code retrieved from the TOTP application.</p>
         * <p>The one-time password code retrieved from the TOTP application.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("otp_code")
        public _FinalStage otpCode(@NotNull String otpCode) {
            this.otpCode = Objects.requireNonNull(otpCode, "otpCode must not be null");
            return this;
        }

        @java.lang.Override
        public VerifyTotpAuthenticationMethod build() {
            return new VerifyTotpAuthenticationMethod(authSession, otpCode, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
