/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = VerifyPasswordAuthenticationMethod.Builder.class)
public final class VerifyPasswordAuthenticationMethod {
    private final String authSession;

    private final String newPassword;

    private final Map<String, Object> additionalProperties;

    private VerifyPasswordAuthenticationMethod(
            String authSession, String newPassword, Map<String, Object> additionalProperties) {
        this.authSession = authSession;
        this.newPassword = newPassword;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique session identifier for the password change operation as returned by POST /authentication-methods
     */
    @JsonProperty("auth_session")
    public String getAuthSession() {
        return authSession;
    }

    /**
     * @return The new password to set for the user
     */
    @JsonProperty("new_password")
    public String getNewPassword() {
        return newPassword;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof VerifyPasswordAuthenticationMethod
                && equalTo((VerifyPasswordAuthenticationMethod) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(VerifyPasswordAuthenticationMethod other) {
        return authSession.equals(other.authSession) && newPassword.equals(other.newPassword);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.authSession, this.newPassword);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AuthSessionStage builder() {
        return new Builder();
    }

    public interface AuthSessionStage {
        /**
         * <p>The unique session identifier for the password change operation as returned by POST /authentication-methods</p>
         */
        NewPasswordStage authSession(@NotNull String authSession);

        Builder from(VerifyPasswordAuthenticationMethod other);
    }

    public interface NewPasswordStage {
        /**
         * <p>The new password to set for the user</p>
         */
        _FinalStage newPassword(@NotNull String newPassword);
    }

    public interface _FinalStage {
        VerifyPasswordAuthenticationMethod build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AuthSessionStage, NewPasswordStage, _FinalStage {
        private String authSession;

        private String newPassword;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(VerifyPasswordAuthenticationMethod other) {
            authSession(other.getAuthSession());
            newPassword(other.getNewPassword());
            return this;
        }

        /**
         * <p>The unique session identifier for the password change operation as returned by POST /authentication-methods</p>
         * <p>The unique session identifier for the password change operation as returned by POST /authentication-methods</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("auth_session")
        public NewPasswordStage authSession(@NotNull String authSession) {
            this.authSession = Objects.requireNonNull(authSession, "authSession must not be null");
            return this;
        }

        /**
         * <p>The new password to set for the user</p>
         * <p>The new password to set for the user</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("new_password")
        public _FinalStage newPassword(@NotNull String newPassword) {
            this.newPassword = Objects.requireNonNull(newPassword, "newPassword must not be null");
            return this;
        }

        @java.lang.Override
        public VerifyPasswordAuthenticationMethod build() {
            return new VerifyPasswordAuthenticationMethod(authSession, newPassword, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
