/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

public final class VerifyAuthenticationMethodResponseContent {
    private final Value value;

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    private VerifyAuthenticationMethodResponseContent(Value value) {
        this.value = value;
    }

    public <T> T visit(Visitor<T> visitor) {
        return value.visit(visitor);
    }

    public static VerifyAuthenticationMethodResponseContent password(AuthenticationMethodPassword value) {
        return new VerifyAuthenticationMethodResponseContent(new PasswordValue(value));
    }

    public static VerifyAuthenticationMethodResponseContent passkey(AuthenticationMethodPasskey value) {
        return new VerifyAuthenticationMethodResponseContent(new PasskeyValue(value));
    }

    public static VerifyAuthenticationMethodResponseContent recoveryCode(AuthenticationMethodMfaRecoveryCode value) {
        return new VerifyAuthenticationMethodResponseContent(new RecoveryCodeValue(value));
    }

    public static VerifyAuthenticationMethodResponseContent pushNotification(
            AuthenticationMethodMfaPushNotification value) {
        return new VerifyAuthenticationMethodResponseContent(new PushNotificationValue(value));
    }

    public static VerifyAuthenticationMethodResponseContent totp(AuthenticationMethodMfaTotp value) {
        return new VerifyAuthenticationMethodResponseContent(new TotpValue(value));
    }

    public static VerifyAuthenticationMethodResponseContent webauthnPlatform(
            AuthenticationMethodWebAuthnPlatform value) {
        return new VerifyAuthenticationMethodResponseContent(new WebauthnPlatformValue(value));
    }

    public static VerifyAuthenticationMethodResponseContent webauthnRoaming(AuthenticationMethodWebAuthnRoaming value) {
        return new VerifyAuthenticationMethodResponseContent(new WebauthnRoamingValue(value));
    }

    public static VerifyAuthenticationMethodResponseContent phone(AuthenticationMethodPhone value) {
        return new VerifyAuthenticationMethodResponseContent(new PhoneValue(value));
    }

    public static VerifyAuthenticationMethodResponseContent email(AuthenticationMethodEmail value) {
        return new VerifyAuthenticationMethodResponseContent(new EmailValue(value));
    }

    public boolean isPassword() {
        return value instanceof PasswordValue;
    }

    public boolean isPasskey() {
        return value instanceof PasskeyValue;
    }

    public boolean isRecoveryCode() {
        return value instanceof RecoveryCodeValue;
    }

    public boolean isPushNotification() {
        return value instanceof PushNotificationValue;
    }

    public boolean isTotp() {
        return value instanceof TotpValue;
    }

    public boolean isWebauthnPlatform() {
        return value instanceof WebauthnPlatformValue;
    }

    public boolean isWebauthnRoaming() {
        return value instanceof WebauthnRoamingValue;
    }

    public boolean isPhone() {
        return value instanceof PhoneValue;
    }

    public boolean isEmail() {
        return value instanceof EmailValue;
    }

    public boolean _isUnknown() {
        return value instanceof _UnknownValue;
    }

    public Optional<AuthenticationMethodPassword> getPassword() {
        if (isPassword()) {
            return Optional.of(((PasswordValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<AuthenticationMethodPasskey> getPasskey() {
        if (isPasskey()) {
            return Optional.of(((PasskeyValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<AuthenticationMethodMfaRecoveryCode> getRecoveryCode() {
        if (isRecoveryCode()) {
            return Optional.of(((RecoveryCodeValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<AuthenticationMethodMfaPushNotification> getPushNotification() {
        if (isPushNotification()) {
            return Optional.of(((PushNotificationValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<AuthenticationMethodMfaTotp> getTotp() {
        if (isTotp()) {
            return Optional.of(((TotpValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<AuthenticationMethodWebAuthnPlatform> getWebauthnPlatform() {
        if (isWebauthnPlatform()) {
            return Optional.of(((WebauthnPlatformValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<AuthenticationMethodWebAuthnRoaming> getWebauthnRoaming() {
        if (isWebauthnRoaming()) {
            return Optional.of(((WebauthnRoamingValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<AuthenticationMethodPhone> getPhone() {
        if (isPhone()) {
            return Optional.of(((PhoneValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<AuthenticationMethodEmail> getEmail() {
        if (isEmail()) {
            return Optional.of(((EmailValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Object> _getUnknown() {
        if (_isUnknown()) {
            return Optional.of(((_UnknownValue) value).value);
        }
        return Optional.empty();
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof VerifyAuthenticationMethodResponseContent
                && value.equals(((VerifyAuthenticationMethodResponseContent) other).value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public String toString() {
        return value.toString();
    }

    @JsonValue
    private Value getValue() {
        return this.value;
    }

    public interface Visitor<T> {
        T visitPassword(AuthenticationMethodPassword password);

        T visitPasskey(AuthenticationMethodPasskey passkey);

        T visitRecoveryCode(AuthenticationMethodMfaRecoveryCode recoveryCode);

        T visitPushNotification(AuthenticationMethodMfaPushNotification pushNotification);

        T visitTotp(AuthenticationMethodMfaTotp totp);

        T visitWebauthnPlatform(AuthenticationMethodWebAuthnPlatform webauthnPlatform);

        T visitWebauthnRoaming(AuthenticationMethodWebAuthnRoaming webauthnRoaming);

        T visitPhone(AuthenticationMethodPhone phone);

        T visitEmail(AuthenticationMethodEmail email);

        T _visitUnknown(Object unknownType);
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = true, defaultImpl = _UnknownValue.class)
    @JsonSubTypes({
        @JsonSubTypes.Type(PasswordValue.class),
        @JsonSubTypes.Type(PasskeyValue.class),
        @JsonSubTypes.Type(RecoveryCodeValue.class),
        @JsonSubTypes.Type(PushNotificationValue.class),
        @JsonSubTypes.Type(TotpValue.class),
        @JsonSubTypes.Type(WebauthnPlatformValue.class),
        @JsonSubTypes.Type(WebauthnRoamingValue.class),
        @JsonSubTypes.Type(PhoneValue.class),
        @JsonSubTypes.Type(EmailValue.class)
    })
    @JsonIgnoreProperties(ignoreUnknown = true)
    private interface Value {
        <T> T visit(Visitor<T> visitor);
    }

    @JsonTypeName("password")
    @JsonIgnoreProperties("type")
    private static final class PasswordValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private AuthenticationMethodPassword value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private PasswordValue() {}

        private PasswordValue(AuthenticationMethodPassword value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitPassword(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof PasswordValue && equalTo((PasswordValue) other);
        }

        private boolean equalTo(PasswordValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "VerifyAuthenticationMethodResponseContent{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("passkey")
    @JsonIgnoreProperties("type")
    private static final class PasskeyValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private AuthenticationMethodPasskey value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private PasskeyValue() {}

        private PasskeyValue(AuthenticationMethodPasskey value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitPasskey(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof PasskeyValue && equalTo((PasskeyValue) other);
        }

        private boolean equalTo(PasskeyValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "VerifyAuthenticationMethodResponseContent{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("recovery-code")
    @JsonIgnoreProperties("type")
    private static final class RecoveryCodeValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private AuthenticationMethodMfaRecoveryCode value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private RecoveryCodeValue() {}

        private RecoveryCodeValue(AuthenticationMethodMfaRecoveryCode value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitRecoveryCode(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof RecoveryCodeValue && equalTo((RecoveryCodeValue) other);
        }

        private boolean equalTo(RecoveryCodeValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "VerifyAuthenticationMethodResponseContent{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("push-notification")
    @JsonIgnoreProperties("type")
    private static final class PushNotificationValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private AuthenticationMethodMfaPushNotification value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private PushNotificationValue() {}

        private PushNotificationValue(AuthenticationMethodMfaPushNotification value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitPushNotification(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof PushNotificationValue && equalTo((PushNotificationValue) other);
        }

        private boolean equalTo(PushNotificationValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "VerifyAuthenticationMethodResponseContent{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("totp")
    @JsonIgnoreProperties("type")
    private static final class TotpValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private AuthenticationMethodMfaTotp value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private TotpValue() {}

        private TotpValue(AuthenticationMethodMfaTotp value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitTotp(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof TotpValue && equalTo((TotpValue) other);
        }

        private boolean equalTo(TotpValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "VerifyAuthenticationMethodResponseContent{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("webauthn-platform")
    @JsonIgnoreProperties("type")
    private static final class WebauthnPlatformValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private AuthenticationMethodWebAuthnPlatform value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private WebauthnPlatformValue() {}

        private WebauthnPlatformValue(AuthenticationMethodWebAuthnPlatform value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitWebauthnPlatform(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof WebauthnPlatformValue && equalTo((WebauthnPlatformValue) other);
        }

        private boolean equalTo(WebauthnPlatformValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "VerifyAuthenticationMethodResponseContent{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("webauthn-roaming")
    @JsonIgnoreProperties("type")
    private static final class WebauthnRoamingValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private AuthenticationMethodWebAuthnRoaming value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private WebauthnRoamingValue() {}

        private WebauthnRoamingValue(AuthenticationMethodWebAuthnRoaming value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitWebauthnRoaming(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof WebauthnRoamingValue && equalTo((WebauthnRoamingValue) other);
        }

        private boolean equalTo(WebauthnRoamingValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "VerifyAuthenticationMethodResponseContent{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("phone")
    @JsonIgnoreProperties("type")
    private static final class PhoneValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private AuthenticationMethodPhone value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private PhoneValue() {}

        private PhoneValue(AuthenticationMethodPhone value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitPhone(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof PhoneValue && equalTo((PhoneValue) other);
        }

        private boolean equalTo(PhoneValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "VerifyAuthenticationMethodResponseContent{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("email")
    @JsonIgnoreProperties("type")
    private static final class EmailValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "type", allowSetters = true)
        private AuthenticationMethodEmail value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private EmailValue() {}

        private EmailValue(AuthenticationMethodEmail value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitEmail(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof EmailValue && equalTo((EmailValue) other);
        }

        private boolean equalTo(EmailValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "VerifyAuthenticationMethodResponseContent{" + "value: " + value + "}";
        }
    }

    @JsonIgnoreProperties("type")
    private static final class _UnknownValue implements Value {
        private String type;

        @JsonValue
        private Object value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private _UnknownValue(@JsonProperty("value") Object value) {}

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor._visitUnknown(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof _UnknownValue && equalTo((_UnknownValue) other);
        }

        private boolean equalTo(_UnknownValue other) {
            return type.equals(other.type) && value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.type, this.value);
        }

        @java.lang.Override
        public String toString() {
            return "VerifyAuthenticationMethodResponseContent{" + "type: " + type + ", value: " + value + "}";
        }
    }
}
