/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = VerifyWebAuthnRoamingAuthenticationMethod.Builder.class)
public final class VerifyWebAuthnRoamingAuthenticationMethod {
    private final String authSession;

    private final AuthenticatorAttestationResponse authnResponse;

    private final Map<String, Object> additionalProperties;

    private VerifyWebAuthnRoamingAuthenticationMethod(
            String authSession,
            AuthenticatorAttestationResponse authnResponse,
            Map<String, Object> additionalProperties) {
        this.authSession = authSession;
        this.authnResponse = authnResponse;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique session identifier for the enrollment as returned by POST /authentication-methods
     */
    @JsonProperty("auth_session")
    public String getAuthSession() {
        return authSession;
    }

    @JsonProperty("authn_response")
    public AuthenticatorAttestationResponse getAuthnResponse() {
        return authnResponse;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof VerifyWebAuthnRoamingAuthenticationMethod
                && equalTo((VerifyWebAuthnRoamingAuthenticationMethod) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(VerifyWebAuthnRoamingAuthenticationMethod other) {
        return authSession.equals(other.authSession) && authnResponse.equals(other.authnResponse);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.authSession, this.authnResponse);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AuthSessionStage builder() {
        return new Builder();
    }

    public interface AuthSessionStage {
        /**
         * <p>The unique session identifier for the enrollment as returned by POST /authentication-methods</p>
         */
        AuthnResponseStage authSession(@NotNull String authSession);

        Builder from(VerifyWebAuthnRoamingAuthenticationMethod other);
    }

    public interface AuthnResponseStage {
        _FinalStage authnResponse(@NotNull AuthenticatorAttestationResponse authnResponse);
    }

    public interface _FinalStage {
        VerifyWebAuthnRoamingAuthenticationMethod build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AuthSessionStage, AuthnResponseStage, _FinalStage {
        private String authSession;

        private AuthenticatorAttestationResponse authnResponse;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(VerifyWebAuthnRoamingAuthenticationMethod other) {
            authSession(other.getAuthSession());
            authnResponse(other.getAuthnResponse());
            return this;
        }

        /**
         * <p>The unique session identifier for the enrollment as returned by POST /authentication-methods</p>
         * <p>The unique session identifier for the enrollment as returned by POST /authentication-methods</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("auth_session")
        public AuthnResponseStage authSession(@NotNull String authSession) {
            this.authSession = Objects.requireNonNull(authSession, "authSession must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("authn_response")
        public _FinalStage authnResponse(@NotNull AuthenticatorAttestationResponse authnResponse) {
            this.authnResponse = Objects.requireNonNull(authnResponse, "authnResponse must not be null");
            return this;
        }

        @java.lang.Override
        public VerifyWebAuthnRoamingAuthenticationMethod build() {
            return new VerifyWebAuthnRoamingAuthenticationMethod(authSession, authnResponse, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
