/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.types;

import com.auth0.client.myaccount.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = VerifyPushNotificationAuthenticationMethod.Builder.class)
public final class VerifyPushNotificationAuthenticationMethod {
    private final String authSession;

    private final Map<String, Object> additionalProperties;

    private VerifyPushNotificationAuthenticationMethod(String authSession, Map<String, Object> additionalProperties) {
        this.authSession = authSession;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique session identifier for the enrollment as returned by POST /authentication-methods
     */
    @JsonProperty("auth_session")
    public String getAuthSession() {
        return authSession;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof VerifyPushNotificationAuthenticationMethod
                && equalTo((VerifyPushNotificationAuthenticationMethod) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(VerifyPushNotificationAuthenticationMethod other) {
        return authSession.equals(other.authSession);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.authSession);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AuthSessionStage builder() {
        return new Builder();
    }

    public interface AuthSessionStage {
        /**
         * <p>The unique session identifier for the enrollment as returned by POST /authentication-methods</p>
         */
        _FinalStage authSession(@NotNull String authSession);

        Builder from(VerifyPushNotificationAuthenticationMethod other);
    }

    public interface _FinalStage {
        VerifyPushNotificationAuthenticationMethod build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AuthSessionStage, _FinalStage {
        private String authSession;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(VerifyPushNotificationAuthenticationMethod other) {
            authSession(other.getAuthSession());
            return this;
        }

        /**
         * <p>The unique session identifier for the enrollment as returned by POST /authentication-methods</p>
         * <p>The unique session identifier for the enrollment as returned by POST /authentication-methods</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("auth_session")
        public _FinalStage authSession(@NotNull String authSession) {
            this.authSession = Objects.requireNonNull(authSession, "authSession must not be null");
            return this;
        }

        @java.lang.Override
        public VerifyPushNotificationAuthenticationMethod build() {
            return new VerifyPushNotificationAuthenticationMethod(authSession, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
