/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount;

import com.auth0.client.myaccount.core.ClientOptions;
import com.auth0.client.myaccount.core.RequestOptions;
import com.auth0.client.myaccount.types.CreateAuthenticationMethodRequestContent;
import com.auth0.client.myaccount.types.CreateAuthenticationMethodResponseContent;
import com.auth0.client.myaccount.types.GetAuthenticationMethodResponseContent;
import com.auth0.client.myaccount.types.ListAuthenticationMethodsRequestParameters;
import com.auth0.client.myaccount.types.ListAuthenticationMethodsResponseContent;
import com.auth0.client.myaccount.types.UpdateAuthenticationMethodRequestContent;
import com.auth0.client.myaccount.types.UpdateAuthenticationMethodResponseContent;
import com.auth0.client.myaccount.types.VerifyAuthenticationMethodRequestContent;
import com.auth0.client.myaccount.types.VerifyAuthenticationMethodResponseContent;
import java.util.concurrent.CompletableFuture;

public class AsyncAuthenticationMethodsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawAuthenticationMethodsClient rawClient;

    public AsyncAuthenticationMethodsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawAuthenticationMethodsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawAuthenticationMethodsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve detailed list of authentication methods belonging to the authenticated user.
     */
    public CompletableFuture<ListAuthenticationMethodsResponseContent> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Retrieve detailed list of authentication methods belonging to the authenticated user.
     */
    public CompletableFuture<ListAuthenticationMethodsResponseContent> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve detailed list of authentication methods belonging to the authenticated user.
     */
    public CompletableFuture<ListAuthenticationMethodsResponseContent> list(
            ListAuthenticationMethodsRequestParameters request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Retrieve detailed list of authentication methods belonging to the authenticated user.
     */
    public CompletableFuture<ListAuthenticationMethodsResponseContent> list(
            ListAuthenticationMethodsRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Start the enrollment of a supported authentication method.
     */
    public CompletableFuture<CreateAuthenticationMethodResponseContent> create(
            CreateAuthenticationMethodRequestContent request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    /**
     * Start the enrollment of a supported authentication method.
     */
    public CompletableFuture<CreateAuthenticationMethodResponseContent> create(
            CreateAuthenticationMethodRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieves a single authentication method belonging to the authenticated user.
     */
    public CompletableFuture<GetAuthenticationMethodResponseContent> get(String authenticationMethodId) {
        return this.rawClient.get(authenticationMethodId).thenApply(response -> response.body());
    }

    /**
     * Retrieves a single authentication method belonging to the authenticated user.
     */
    public CompletableFuture<GetAuthenticationMethodResponseContent> get(
            String authenticationMethodId, RequestOptions requestOptions) {
        return this.rawClient.get(authenticationMethodId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Deletes a single authentication method belonging to the authenticated user.
     */
    public CompletableFuture<Void> delete(String authenticationMethodId) {
        return this.rawClient.delete(authenticationMethodId).thenApply(response -> response.body());
    }

    /**
     * Deletes a single authentication method belonging to the authenticated user.
     */
    public CompletableFuture<Void> delete(String authenticationMethodId, RequestOptions requestOptions) {
        return this.rawClient.delete(authenticationMethodId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Updates a single authentication method
     */
    public CompletableFuture<UpdateAuthenticationMethodResponseContent> update(String authenticationMethodId) {
        return this.rawClient.update(authenticationMethodId).thenApply(response -> response.body());
    }

    /**
     * Updates a single authentication method
     */
    public CompletableFuture<UpdateAuthenticationMethodResponseContent> update(
            String authenticationMethodId, RequestOptions requestOptions) {
        return this.rawClient.update(authenticationMethodId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Updates a single authentication method
     */
    public CompletableFuture<UpdateAuthenticationMethodResponseContent> update(
            String authenticationMethodId, UpdateAuthenticationMethodRequestContent request) {
        return this.rawClient.update(authenticationMethodId, request).thenApply(response -> response.body());
    }

    /**
     * Updates a single authentication method
     */
    public CompletableFuture<UpdateAuthenticationMethodResponseContent> update(
            String authenticationMethodId,
            UpdateAuthenticationMethodRequestContent request,
            RequestOptions requestOptions) {
        return this.rawClient
                .update(authenticationMethodId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Confirm the enrollment of a supported authentication method.
     */
    public CompletableFuture<VerifyAuthenticationMethodResponseContent> verify(
            String authenticationMethodId, VerifyAuthenticationMethodRequestContent request) {
        return this.rawClient.verify(authenticationMethodId, request).thenApply(response -> response.body());
    }

    /**
     * Confirm the enrollment of a supported authentication method.
     */
    public CompletableFuture<VerifyAuthenticationMethodResponseContent> verify(
            String authenticationMethodId,
            VerifyAuthenticationMethodRequestContent request,
            RequestOptions requestOptions) {
        return this.rawClient
                .verify(authenticationMethodId, request, requestOptions)
                .thenApply(response -> response.body());
    }
}
