/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount;

import com.auth0.client.myaccount.core.ClientOptions;
import com.auth0.client.myaccount.core.RequestOptions;
import com.auth0.client.myaccount.types.ListFactorsResponseContent;
import java.util.concurrent.CompletableFuture;

public class AsyncFactorsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawFactorsClient rawClient;

    public AsyncFactorsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawFactorsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawFactorsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * List of factors enabled for the Auth0 tenant and available for enrollment by this user.
     */
    public CompletableFuture<ListFactorsResponseContent> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * List of factors enabled for the Auth0 tenant and available for enrollment by this user.
     */
    public CompletableFuture<ListFactorsResponseContent> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }
}
