/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount;

import com.auth0.client.myaccount.core.ClientOptions;
import com.auth0.client.myaccount.core.Suppliers;
import java.util.function.Supplier;

public class AsyncMyAccountApi {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncFactorsClient> factorsClient;

    protected final Supplier<AsyncAuthenticationMethodsClient> authenticationMethodsClient;

    protected final Supplier<AsyncConnectedAccountsClient> connectedAccountsClient;

    public AsyncMyAccountApi(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.factorsClient = Suppliers.memoize(() -> new AsyncFactorsClient(clientOptions));
        this.authenticationMethodsClient = Suppliers.memoize(() -> new AsyncAuthenticationMethodsClient(clientOptions));
        this.connectedAccountsClient = Suppliers.memoize(() -> new AsyncConnectedAccountsClient(clientOptions));
    }

    public AsyncFactorsClient factors() {
        return this.factorsClient.get();
    }

    public AsyncAuthenticationMethodsClient authenticationMethods() {
        return this.authenticationMethodsClient.get();
    }

    public AsyncConnectedAccountsClient connectedAccounts() {
        return this.connectedAccountsClient.get();
    }

    public static AsyncMyAccountApiBuilder builder() {
        return new AsyncMyAccountApiBuilder();
    }
}
