/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount;

import com.auth0.client.myaccount.connectedaccounts.AsyncConnectionsClient;
import com.auth0.client.myaccount.core.ClientOptions;
import com.auth0.client.myaccount.core.RequestOptions;
import com.auth0.client.myaccount.core.Suppliers;
import com.auth0.client.myaccount.core.SyncPagingIterable;
import com.auth0.client.myaccount.types.CompleteConnectedAccountsRequestContent;
import com.auth0.client.myaccount.types.CompleteConnectedAccountsResponseContent;
import com.auth0.client.myaccount.types.ConnectedAccount;
import com.auth0.client.myaccount.types.CreateConnectedAccountsRequestContent;
import com.auth0.client.myaccount.types.CreateConnectedAccountsResponseContent;
import com.auth0.client.myaccount.types.ListConnectedAccountsRequestParameters;
import java.util.concurrent.CompletableFuture;
import java.util.function.Supplier;

public class AsyncConnectedAccountsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawConnectedAccountsClient rawClient;

    protected final Supplier<AsyncConnectionsClient> connectionsClient;

    public AsyncConnectedAccountsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawConnectedAccountsClient(clientOptions);
        this.connectionsClient = Suppliers.memoize(() -> new AsyncConnectionsClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawConnectedAccountsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Start an authorization flow to link the authenticated user's account with an external identity provider.
     */
    public CompletableFuture<CreateConnectedAccountsResponseContent> create(
            CreateConnectedAccountsRequestContent request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    /**
     * Start an authorization flow to link the authenticated user's account with an external identity provider.
     */
    public CompletableFuture<CreateConnectedAccountsResponseContent> create(
            CreateConnectedAccountsRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Complete a previously started authorization flow to link the authenticated user's account with an external identity provider.
     */
    public CompletableFuture<CompleteConnectedAccountsResponseContent> complete(
            CompleteConnectedAccountsRequestContent request) {
        return this.rawClient.complete(request).thenApply(response -> response.body());
    }

    /**
     * Complete a previously started authorization flow to link the authenticated user's account with an external identity provider.
     */
    public CompletableFuture<CompleteConnectedAccountsResponseContent> complete(
            CompleteConnectedAccountsRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.complete(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve connected accounts belonging to the authenticated user.
     */
    public CompletableFuture<SyncPagingIterable<ConnectedAccount>> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Retrieve connected accounts belonging to the authenticated user.
     */
    public CompletableFuture<SyncPagingIterable<ConnectedAccount>> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve connected accounts belonging to the authenticated user.
     */
    public CompletableFuture<SyncPagingIterable<ConnectedAccount>> list(
            ListConnectedAccountsRequestParameters request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Retrieve connected accounts belonging to the authenticated user.
     */
    public CompletableFuture<SyncPagingIterable<ConnectedAccount>> list(
            ListConnectedAccountsRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Delete a connected account belonging to the authenticated user.
     */
    public CompletableFuture<Void> delete(String id) {
        return this.rawClient.delete(id).thenApply(response -> response.body());
    }

    /**
     * Delete a connected account belonging to the authenticated user.
     */
    public CompletableFuture<Void> delete(String id, RequestOptions requestOptions) {
        return this.rawClient.delete(id, requestOptions).thenApply(response -> response.body());
    }

    public AsyncConnectionsClient connections() {
        return this.connectionsClient.get();
    }
}
