/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount;

import com.auth0.client.myaccount.core.ClientOptions;
import com.auth0.client.myaccount.core.RequestOptions;
import com.auth0.client.myaccount.types.CreateAuthenticationMethodRequestContent;
import com.auth0.client.myaccount.types.CreateAuthenticationMethodResponseContent;
import com.auth0.client.myaccount.types.GetAuthenticationMethodResponseContent;
import com.auth0.client.myaccount.types.ListAuthenticationMethodsRequestParameters;
import com.auth0.client.myaccount.types.ListAuthenticationMethodsResponseContent;
import com.auth0.client.myaccount.types.UpdateAuthenticationMethodRequestContent;
import com.auth0.client.myaccount.types.UpdateAuthenticationMethodResponseContent;
import com.auth0.client.myaccount.types.VerifyAuthenticationMethodRequestContent;
import com.auth0.client.myaccount.types.VerifyAuthenticationMethodResponseContent;

public class AuthenticationMethodsClient {
    protected final ClientOptions clientOptions;

    private final RawAuthenticationMethodsClient rawClient;

    public AuthenticationMethodsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawAuthenticationMethodsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawAuthenticationMethodsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve detailed list of authentication methods belonging to the authenticated user.
     */
    public ListAuthenticationMethodsResponseContent list() {
        return this.rawClient.list().body();
    }

    /**
     * Retrieve detailed list of authentication methods belonging to the authenticated user.
     */
    public ListAuthenticationMethodsResponseContent list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    /**
     * Retrieve detailed list of authentication methods belonging to the authenticated user.
     */
    public ListAuthenticationMethodsResponseContent list(ListAuthenticationMethodsRequestParameters request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Retrieve detailed list of authentication methods belonging to the authenticated user.
     */
    public ListAuthenticationMethodsResponseContent list(
            ListAuthenticationMethodsRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    /**
     * Start the enrollment of a supported authentication method.
     */
    public CreateAuthenticationMethodResponseContent create(CreateAuthenticationMethodRequestContent request) {
        return this.rawClient.create(request).body();
    }

    /**
     * Start the enrollment of a supported authentication method.
     */
    public CreateAuthenticationMethodResponseContent create(
            CreateAuthenticationMethodRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }

    /**
     * Retrieves a single authentication method belonging to the authenticated user.
     */
    public GetAuthenticationMethodResponseContent get(String authenticationMethodId) {
        return this.rawClient.get(authenticationMethodId).body();
    }

    /**
     * Retrieves a single authentication method belonging to the authenticated user.
     */
    public GetAuthenticationMethodResponseContent get(String authenticationMethodId, RequestOptions requestOptions) {
        return this.rawClient.get(authenticationMethodId, requestOptions).body();
    }

    /**
     * Deletes a single authentication method belonging to the authenticated user.
     */
    public void delete(String authenticationMethodId) {
        this.rawClient.delete(authenticationMethodId).body();
    }

    /**
     * Deletes a single authentication method belonging to the authenticated user.
     */
    public void delete(String authenticationMethodId, RequestOptions requestOptions) {
        this.rawClient.delete(authenticationMethodId, requestOptions).body();
    }

    /**
     * Updates a single authentication method
     */
    public UpdateAuthenticationMethodResponseContent update(String authenticationMethodId) {
        return this.rawClient.update(authenticationMethodId).body();
    }

    /**
     * Updates a single authentication method
     */
    public UpdateAuthenticationMethodResponseContent update(
            String authenticationMethodId, RequestOptions requestOptions) {
        return this.rawClient.update(authenticationMethodId, requestOptions).body();
    }

    /**
     * Updates a single authentication method
     */
    public UpdateAuthenticationMethodResponseContent update(
            String authenticationMethodId, UpdateAuthenticationMethodRequestContent request) {
        return this.rawClient.update(authenticationMethodId, request).body();
    }

    /**
     * Updates a single authentication method
     */
    public UpdateAuthenticationMethodResponseContent update(
            String authenticationMethodId,
            UpdateAuthenticationMethodRequestContent request,
            RequestOptions requestOptions) {
        return this.rawClient
                .update(authenticationMethodId, request, requestOptions)
                .body();
    }

    /**
     * Confirm the enrollment of a supported authentication method.
     */
    public VerifyAuthenticationMethodResponseContent verify(
            String authenticationMethodId, VerifyAuthenticationMethodRequestContent request) {
        return this.rawClient.verify(authenticationMethodId, request).body();
    }

    /**
     * Confirm the enrollment of a supported authentication method.
     */
    public VerifyAuthenticationMethodResponseContent verify(
            String authenticationMethodId,
            VerifyAuthenticationMethodRequestContent request,
            RequestOptions requestOptions) {
        return this.rawClient
                .verify(authenticationMethodId, request, requestOptions)
                .body();
    }
}
