/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount;

import com.auth0.client.myaccount.core.ClientOptions;
import com.auth0.client.myaccount.core.Suppliers;
import java.util.function.Supplier;

public class MyAccountApi {
    protected final ClientOptions clientOptions;

    protected final Supplier<FactorsClient> factorsClient;

    protected final Supplier<AuthenticationMethodsClient> authenticationMethodsClient;

    protected final Supplier<ConnectedAccountsClient> connectedAccountsClient;

    public MyAccountApi(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.factorsClient = Suppliers.memoize(() -> new FactorsClient(clientOptions));
        this.authenticationMethodsClient = Suppliers.memoize(() -> new AuthenticationMethodsClient(clientOptions));
        this.connectedAccountsClient = Suppliers.memoize(() -> new ConnectedAccountsClient(clientOptions));
    }

    public FactorsClient factors() {
        return this.factorsClient.get();
    }

    public AuthenticationMethodsClient authenticationMethods() {
        return this.authenticationMethodsClient.get();
    }

    public ConnectedAccountsClient connectedAccounts() {
        return this.connectedAccountsClient.get();
    }

    public static MyAccountApiBuilder builder() {
        return new MyAccountApiBuilder();
    }
}
