/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount;

import com.auth0.client.myaccount.core.ClientOptions;
import com.auth0.client.myaccount.core.MediaTypes;
import com.auth0.client.myaccount.core.MyAccountApiException;
import com.auth0.client.myaccount.core.MyAccountApiHttpResponse;
import com.auth0.client.myaccount.core.MyAccountException;
import com.auth0.client.myaccount.core.ObjectMappers;
import com.auth0.client.myaccount.core.QueryStringMapper;
import com.auth0.client.myaccount.core.RequestOptions;
import com.auth0.client.myaccount.errors.BadRequestError;
import com.auth0.client.myaccount.errors.ConflictError;
import com.auth0.client.myaccount.errors.ForbiddenError;
import com.auth0.client.myaccount.errors.NotFoundError;
import com.auth0.client.myaccount.errors.TooManyRequestsError;
import com.auth0.client.myaccount.errors.UnauthorizedError;
import com.auth0.client.myaccount.errors.UnsupportedMediaTypeError;
import com.auth0.client.myaccount.types.CreateAuthenticationMethodRequestContent;
import com.auth0.client.myaccount.types.CreateAuthenticationMethodResponseContent;
import com.auth0.client.myaccount.types.ErrorResponse;
import com.auth0.client.myaccount.types.GetAuthenticationMethodResponseContent;
import com.auth0.client.myaccount.types.ListAuthenticationMethodsRequestParameters;
import com.auth0.client.myaccount.types.ListAuthenticationMethodsResponseContent;
import com.auth0.client.myaccount.types.UpdateAuthenticationMethodRequestContent;
import com.auth0.client.myaccount.types.UpdateAuthenticationMethodResponseContent;
import com.auth0.client.myaccount.types.VerifyAuthenticationMethodRequestContent;
import com.auth0.client.myaccount.types.VerifyAuthenticationMethodResponseContent;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawAuthenticationMethodsClient {
    protected final ClientOptions clientOptions;

    public RawAuthenticationMethodsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Retrieve detailed list of authentication methods belonging to the authenticated user.
     */
    public MyAccountApiHttpResponse<ListAuthenticationMethodsResponseContent> list() {
        return list(ListAuthenticationMethodsRequestParameters.builder().build());
    }

    /**
     * Retrieve detailed list of authentication methods belonging to the authenticated user.
     */
    public MyAccountApiHttpResponse<ListAuthenticationMethodsResponseContent> list(RequestOptions requestOptions) {
        return list(ListAuthenticationMethodsRequestParameters.builder().build(), requestOptions);
    }

    /**
     * Retrieve detailed list of authentication methods belonging to the authenticated user.
     */
    public MyAccountApiHttpResponse<ListAuthenticationMethodsResponseContent> list(
            ListAuthenticationMethodsRequestParameters request) {
        return list(request, null);
    }

    /**
     * Retrieve detailed list of authentication methods belonging to the authenticated user.
     */
    public MyAccountApiHttpResponse<ListAuthenticationMethodsResponseContent> list(
            ListAuthenticationMethodsRequestParameters request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("authentication-methods");
        if (!request.getType().isAbsent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "type", request.getType().orElse(null), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MyAccountApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, ListAuthenticationMethodsResponseContent.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MyAccountApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new MyAccountException("Network error executing HTTP request", e);
        }
    }

    /**
     * Start the enrollment of a supported authentication method.
     */
    public MyAccountApiHttpResponse<CreateAuthenticationMethodResponseContent> create(
            CreateAuthenticationMethodRequestContent request) {
        return create(request, null);
    }

    /**
     * Start the enrollment of a supported authentication method.
     */
    public MyAccountApiHttpResponse<CreateAuthenticationMethodResponseContent> create(
            CreateAuthenticationMethodRequestContent request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("authentication-methods");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MyAccountException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MyAccountApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, CreateAuthenticationMethodResponseContent.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 415:
                        throw new UnsupportedMediaTypeError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MyAccountApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new MyAccountException("Network error executing HTTP request", e);
        }
    }

    /**
     * Retrieves a single authentication method belonging to the authenticated user.
     */
    public MyAccountApiHttpResponse<GetAuthenticationMethodResponseContent> get(String authenticationMethodId) {
        return get(authenticationMethodId, null);
    }

    /**
     * Retrieves a single authentication method belonging to the authenticated user.
     */
    public MyAccountApiHttpResponse<GetAuthenticationMethodResponseContent> get(
            String authenticationMethodId, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("authentication-methods")
                .addPathSegment(authenticationMethodId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MyAccountApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, GetAuthenticationMethodResponseContent.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MyAccountApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new MyAccountException("Network error executing HTTP request", e);
        }
    }

    /**
     * Deletes a single authentication method belonging to the authenticated user.
     */
    public MyAccountApiHttpResponse<Void> delete(String authenticationMethodId) {
        return delete(authenticationMethodId, null);
    }

    /**
     * Deletes a single authentication method belonging to the authenticated user.
     */
    public MyAccountApiHttpResponse<Void> delete(String authenticationMethodId, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("authentication-methods")
                .addPathSegment(authenticationMethodId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new MyAccountApiHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 409:
                        throw new ConflictError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MyAccountApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new MyAccountException("Network error executing HTTP request", e);
        }
    }

    /**
     * Updates a single authentication method
     */
    public MyAccountApiHttpResponse<UpdateAuthenticationMethodResponseContent> update(String authenticationMethodId) {
        return update(
                authenticationMethodId,
                UpdateAuthenticationMethodRequestContent.builder().build());
    }

    /**
     * Updates a single authentication method
     */
    public MyAccountApiHttpResponse<UpdateAuthenticationMethodResponseContent> update(
            String authenticationMethodId, RequestOptions requestOptions) {
        return update(
                authenticationMethodId,
                UpdateAuthenticationMethodRequestContent.builder().build(),
                requestOptions);
    }

    /**
     * Updates a single authentication method
     */
    public MyAccountApiHttpResponse<UpdateAuthenticationMethodResponseContent> update(
            String authenticationMethodId, UpdateAuthenticationMethodRequestContent request) {
        return update(authenticationMethodId, request, null);
    }

    /**
     * Updates a single authentication method
     */
    public MyAccountApiHttpResponse<UpdateAuthenticationMethodResponseContent> update(
            String authenticationMethodId,
            UpdateAuthenticationMethodRequestContent request,
            RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("authentication-methods")
                .addPathSegment(authenticationMethodId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MyAccountException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MyAccountApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, UpdateAuthenticationMethodResponseContent.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 415:
                        throw new UnsupportedMediaTypeError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MyAccountApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new MyAccountException("Network error executing HTTP request", e);
        }
    }

    /**
     * Confirm the enrollment of a supported authentication method.
     */
    public MyAccountApiHttpResponse<VerifyAuthenticationMethodResponseContent> verify(
            String authenticationMethodId, VerifyAuthenticationMethodRequestContent request) {
        return verify(authenticationMethodId, request, null);
    }

    /**
     * Confirm the enrollment of a supported authentication method.
     */
    public MyAccountApiHttpResponse<VerifyAuthenticationMethodResponseContent> verify(
            String authenticationMethodId,
            VerifyAuthenticationMethodRequestContent request,
            RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("authentication-methods")
                .addPathSegment(authenticationMethodId)
                .addPathSegments("verify");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MyAccountException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MyAccountApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, VerifyAuthenticationMethodResponseContent.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 415:
                        throw new UnsupportedMediaTypeError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MyAccountApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new MyAccountException("Network error executing HTTP request", e);
        }
    }
}
