/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.connectedaccounts;

import com.auth0.client.myaccount.connectedaccounts.types.ListConnectedAccountsConnectionsRequestParameters;
import com.auth0.client.myaccount.core.ClientOptions;
import com.auth0.client.myaccount.core.RequestOptions;
import com.auth0.client.myaccount.core.SyncPagingIterable;
import com.auth0.client.myaccount.types.ConnectedAccountConnection;

public class ConnectionsClient {
    protected final ClientOptions clientOptions;

    private final RawConnectionsClient rawClient;

    public ConnectionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawConnectionsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawConnectionsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve available connections that can be used for account linking by the authenticated user.
     */
    public SyncPagingIterable<ConnectedAccountConnection> list() {
        return this.rawClient.list().body();
    }

    /**
     * Retrieve available connections that can be used for account linking by the authenticated user.
     */
    public SyncPagingIterable<ConnectedAccountConnection> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    /**
     * Retrieve available connections that can be used for account linking by the authenticated user.
     */
    public SyncPagingIterable<ConnectedAccountConnection> list(
            ListConnectedAccountsConnectionsRequestParameters request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Retrieve available connections that can be used for account linking by the authenticated user.
     */
    public SyncPagingIterable<ConnectedAccountConnection> list(
            ListConnectedAccountsConnectionsRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }
}
