/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.connectedaccounts;

import com.auth0.client.myaccount.connectedaccounts.types.ListConnectedAccountsConnectionsRequestParameters;
import com.auth0.client.myaccount.core.ClientOptions;
import com.auth0.client.myaccount.core.MyAccountApiException;
import com.auth0.client.myaccount.core.MyAccountApiHttpResponse;
import com.auth0.client.myaccount.core.MyAccountException;
import com.auth0.client.myaccount.core.ObjectMappers;
import com.auth0.client.myaccount.core.QueryStringMapper;
import com.auth0.client.myaccount.core.RequestOptions;
import com.auth0.client.myaccount.core.SyncPagingIterable;
import com.auth0.client.myaccount.errors.BadRequestError;
import com.auth0.client.myaccount.errors.ForbiddenError;
import com.auth0.client.myaccount.errors.TooManyRequestsError;
import com.auth0.client.myaccount.errors.UnauthorizedError;
import com.auth0.client.myaccount.types.ConnectedAccountConnection;
import com.auth0.client.myaccount.types.ErrorResponse;
import com.auth0.client.myaccount.types.ListConnectedAccountsConnectionsResponseContent;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.util.List;
import java.util.Optional;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawConnectionsClient {
    protected final ClientOptions clientOptions;

    public RawConnectionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Retrieve available connections that can be used for account linking by the authenticated user.
     */
    public MyAccountApiHttpResponse<SyncPagingIterable<ConnectedAccountConnection>> list() {
        return list(ListConnectedAccountsConnectionsRequestParameters.builder().build());
    }

    /**
     * Retrieve available connections that can be used for account linking by the authenticated user.
     */
    public MyAccountApiHttpResponse<SyncPagingIterable<ConnectedAccountConnection>> list(
            RequestOptions requestOptions) {
        return list(ListConnectedAccountsConnectionsRequestParameters.builder().build(), requestOptions);
    }

    /**
     * Retrieve available connections that can be used for account linking by the authenticated user.
     */
    public MyAccountApiHttpResponse<SyncPagingIterable<ConnectedAccountConnection>> list(
            ListConnectedAccountsConnectionsRequestParameters request) {
        return list(request, null);
    }

    /**
     * Retrieve available connections that can be used for account linking by the authenticated user.
     */
    public MyAccountApiHttpResponse<SyncPagingIterable<ConnectedAccountConnection>> list(
            ListConnectedAccountsConnectionsRequestParameters request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("connected-accounts/connections");
        if (!request.getFrom().isAbsent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "from", request.getFrom().orElse(null), false);
        }
        QueryStringMapper.addQueryParameter(httpUrl, "take", request.getTake().orElse(10), false);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                ListConnectedAccountsConnectionsResponseContent parsedResponse = ObjectMappers.JSON_MAPPER.readValue(
                        responseBodyString, ListConnectedAccountsConnectionsResponseContent.class);
                Optional<String> startingAfter = parsedResponse.getNext();
                ListConnectedAccountsConnectionsRequestParameters nextRequest =
                        ListConnectedAccountsConnectionsRequestParameters.builder()
                                .from(request)
                                .from(startingAfter)
                                .build();
                List<ConnectedAccountConnection> result = parsedResponse.getConnections();
                return new MyAccountApiHttpResponse<>(
                        new SyncPagingIterable<ConnectedAccountConnection>(
                                startingAfter.isPresent(), result, parsedResponse, () -> list(
                                                nextRequest, requestOptions)
                                        .body()),
                        response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MyAccountApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new MyAccountException("Network error executing HTTP request", e);
        }
    }
}
