name: Publish release to Java

inputs:
  java-version:
    required: true
  ossr-username:
    required: true
  ossr-token:
    required: true
  signing-key:
    required: true
  signing-password:
    required: true

runs:
  using: composite

  steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Setup Java
      shell: bash
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "/home/runner/.sdkman/bin/sdkman-init.sh"
        sdk list java
        sdk install java ${{ inputs.java-version }} && sdk default java ${{ inputs.java-version }}

    - uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

    - name: Publish Packages to Maven
      shell: bash
      run: ./gradlew publishToSonatype closeSonatypeStagingRepository -PisSnapshot=false --stacktrace
      env:
        MAVEN_USERNAME: ${{ inputs.ossr-username }}
        MAVEN_PASSWORD: ${{ inputs.ossr-token }}
        SIGNING_KEY: ${{ inputs.signing-key }}
        SIGNING_PASSWORD: ${{ inputs.signing-password }}
