/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myaccount.errors;

import com.auth0.client.myaccount.core.MyAccountApiException;
import com.auth0.client.myaccount.types.ErrorResponse;
import okhttp3.Response;

public final class UnauthorizedError extends MyAccountApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final ErrorResponse body;

    public UnauthorizedError(ErrorResponse body) {
        super("UnauthorizedError", 401, body);
        this.body = body;
    }

    public UnauthorizedError(ErrorResponse body, Response rawResponse) {
        super("UnauthorizedError", 401, body, rawResponse);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public ErrorResponse body() {
        return this.body;
    }
}
